package model;

/**
 * Created by SStrombe on 6/11/16.
 */
public class Profession {
    public static int INDEX_PROFESSION_TITLE = 0;
    public static int INDEX_PROFESSION_SALARY = 1;

    public static String[][] professions = new String[][] {
        {"Retail Sales Workers", "24490"},
        {"Food and Beverage Serving Workers", "21430"},
        {"Information and Record Clerks", "33610"},
        {"Health Diagnosing and Treating Practitioners", "97030"},
        {"Retail Salespersons", "26340"},
        {"Material Moving Workers", "28710"},
        {"Business Operations Specialists", "70900"},
        {"Preschool, Primary, Secondary, and Special Education School Teachers", "56370"},
        {"Construction Trades Workers", "46290"},
        {"Material Recording, Scheduling, Dispatching, and Distributing Workers", "33610"},
        {"Other Office and Administrative Support Workers", "32800"},
        {"Motor Vehicle Operators", "36460"},
        {"Fast Food and Counter Workers", "19820"},
        {"Secretaries and Administrative Assistants", "39360"},
        {"Laborers and Material Movers, Hand", "26760"},
        {"Cashiers", "21010"},
        {"Cashiers", "20990"},
        {"Combined Food Preparation and Serving Workers, Including Fast Food", "19710"},
        {"Financial Clerks", "36680"},
        {"Building Cleaning and Pest Control Workers", "25440"},
        {"Cooks and Food Preparation Workers", "22990"},
        {"Building Cleaning Workers", "25240"},
        {"Office Clerks, General", "31890"},
        {"Driver/Sales Workers and Truck Drivers", "38030"},
        {"Health Technologists and Technicians", "45850"},
        {"Registered Nurses", "71000"},
        {"Other Personal Care and Service Workers", "24480"},
        {"Financial Specialists", "78730"},
        {"Customer Service Representatives", "34560"},
        {"Waiters and Waitresses", "23020"},
        {"Laborers and Freight, Stock, and Material Movers, Hand", "27840"},
        {"Top Executives", "124210"},
        {"Nursing, Psychiatric, and Home Health Aides", "25500"},
        {"Cooks", "23350"},
        {"Secretaries and Administrative Assistants, Except Legal, Medical, and Executive", "35200"},
        {"Janitors and Cleaners, Except Maids and Housekeeping Cleaners", "26180"},
        {"General and Operations Managers", "119460"},
        {"Elementary and Middle School Teachers", "58060"},
        {"Metal Workers and Plastic Workers", "38850"},
        {"Stock Clerks and Order Fillers", "25940"},
        {"Counselors, Social Workers, and Other Community and Social Service Specialists", "46170"},
        {"Sales Representatives, Services", "69100"},
        {"Assembler", "32670"},
        {"Sales Representatives, Wholesale and Manufacturing", "71080"},
        {"Heavy and Tractor-Trailer Truck Drivers", "42500"},
        {"Operations Specialties Managers", "120900"},
        {"Engineers", "95240"},
        {"Auditing Clerk", "38990"},
        {"Software Developers and Programmers", "97930"},
        {"Vehicle and Mobile Equipment Mechanics, Installers, and Repairers", "42990"},
        {"Postsecondary Teachers", "77480"},
        {"Other Protective Service Workers", "29050"},
        {"First-Line Supervisors of Sales Workers", "50120"},
        {"First-Line Supervisors of Office and Administrative Support Workers", "56170"},
        {"Nursing Assistants", "26820"},
        {"Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products", "66790"},
        {"Elementary School Teachers, Except Special Education", "57730"},
        {"Personal Care Aides", "21790"},
        {"Other Food Preparation and Serving Related Workers", "20830"},
        {"Maintenance and Repair Workers, General", "38950"},
        {"Teacher Assistants", "26550"},
        {"Accountant", "75280"},
        {"Law Enforcement Workers", "56860"},
        {"First-Line Supervisors of Retail Sales Workers", "42900"},
        {"Other Teachers and Instructors", "37420"},
        {"Cooks, Restaurant", "24430"},
        {"Team Assemblers", "31560"},
        {"Security Guards and Gaming Surveillance Officers", "28510"},
        {"Security Guards", "28460"},
        {"Secondary School Teachers", "60270"},
        {"Supervisors of Food Preparation and Serving Workers", "34930"},
        {"Grounds Maintenance Workers", "28090"},
        {"Receptionists and Information Clerks", "28430"},
        {"Secondary School Teachers, Except Special and Career/Technical Education", "60440"},
        {"Business Operations Specialists, All Other", "73480"},
        {"Maids and Housekeeping Cleaners", "22990"},
        {"Landscaping and Groundskeeping Workers", "27460"},
        {"Construction Laborers", "36550"},
        {"Sales Representatives, Services, All Other", "62360"},
        {"First-Line Supervisors of Food Preparation and Serving Workers", "33330"},
        {"Food Preparation Workers", "22050"},
        {"Light Truck or Delivery Services Drivers", "34080"},
        {"Home Health Aides", "22870"},
        {"Automotive Technician", "41290"},
        {"Food Processing Workers", "27500"},
        {"Computer Support Specialists", "55980"},
        {"Software Developers, Applications", "102160"},
        {"Packers and Packagers, Hand", "23710"},
        {"Health Practitioner Support Technologists and Technicians", "34710"},
        {"Licensed Practical and Licensed Vocational Nurses", "44030"},
        {"Drafters, Engineering Technicians, and Mapping Technicians", "56650"},
        {"Counter and Rental Clerks and Parts Salespersons", "29790"},
        {"Shipping, Receiving, and Traffic Clerks", "32350"},
        {"Bus Drivers", "32980"},
        {"Lawyers, Judges, and Related Workers", "132380"},
        {"Other Sales and Related Workers", "47780"},
        {"Executive Secretaries and Executive Administrative Assistants", "55460"},
        {"Police Officers", "61270"},
        {"Police and Sheriff's Patrol Officers", "61270"},
        {"Sales Manager", "131670"},
        {"Computer and Information Analysts", "90600"},
        {"Physicians and Surgeons", "202450"},
        {"Carpenters", "46780"},
        {"Automotive Service Technician", "40720"},
        {"Database and Systems Administrators and Network Architects", "87400"},
        {"Middle School Teachers, Except Special and Career/Technical Education", "58760"},
        {"Counselors", "48790"},
        {"Therapists", "76220"},
        {"Substitute Teachers", "29630"},
        {"Lawyers and Judicial Law Clerks", "134710"},
        {"Social Workers", "49670"},
        {"Management Analysts", "91770"},
        {"Lawyers", "136260"},
        {"First-Line Supervisors of Production and Operating Workers", "59930"},
        {"Medical Assistants", "31910"},
        {"Electricians", "55590"},
        {"Bartender", "24110"},
        {"Electrical and Electronic Equipment Mechanics, Installers, and Repairers", "50380"},
        {"Computer User Support Specialists", "52430"},
        {"Textile, Apparel, and Furnishings Workers", "25420"},
        {"Recreation and Fitness Workers", "32560"},
        {"Childcare Workers", "22310"},
        {"Human Resources Workers", "63280"},
        {"Media and Communication Workers", "61910"},
        {"Art and Design Worker", "52240"},
        {"Marketing and Sales Managers", "133950"},
        {"Computer Systems Analysts", "90180"},
        {"Financial Analysts and Advisors", "99730"},
        {"Entertainment Attendants and Related Workers", "22140"},
        {"Industrial Truck and Tractor Operators", "34090"},
        {"Financial Managers", "134330"},
        {"Medical Secretaries", "34330"},
        {"Preschool and Kindergarten Teachers", "39090"},
        {"Cooks, Fast Food", "19610"},
        {"First-Line Supervisors of Construction Trades and Extraction Workers", "66820"},
        {"Inspectors, Testers, Sorters, Samplers, and Weighers", "39410"},
        {"Market Research Analysts and Marketing Specialists", "70030"},
        {"Bus Drivers, School or Special Client", "30580"},
        {"Dishwashers", "20360"},
        {"Personal Appearance Workers", "28420"},
        {"Postal Service Workers", "50700"},
        {"Tellers", "27260"},
        {"Entertainers and Performers, Sports and Related Workers", "58380"},
        {"Human Resources Specialists", "63710"},
        {"Billing and Posting Clerk", "36300"},
        {"Counter Attendants, Cafeteria, Food Concession, and Coffee Shop", "20590"},
        {"Special Education Teachers", "59800"},
        {"Designers", "47370"},
        {"Industrial Machinery Installation, Repair, and Maintenance Workers", "50160"},
        {"Education Administrators", "90970"},
        {"Counter and Rental Clerks", "28210"},
        {"Correctional Officer", "45310"},
        {"First-Line Supervisors of Mechanics, Installers, and Repairers", "65890"},
        {"Welding, Soldering, and Brazing Workers", "40560"},
        {"Helpers--Production Workers", "26010"},
        {"Engineering Technicians, Except Drafters", "58490"},
        {"Pipelayers, Plumbers, Pipefitters, and Steamfitters", "53860"},
        {"Correctional Officers and Jailers", "45320"},
        {"Driver/Sales Workers", "27890"},
        {"Buyers and Purchasing Agents", "64170"},
        {"Dining Room and Cafeteria Attendants and Bartender Helpers", "21400"},
        {"Construction Equipment Operators", "48380"},
        {"Cooks, Institution and Cafeteria", "25560"},
        {"Machinists", "42120"},
        {"Other Construction and Related Workers", "46370"},
        {"Plumbers, Pipefitters, and Steamfitters", "55100"},
        {"Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop", "20530"},
        {"Software Developers, Systems Software", "108760"},
        {"Legal Support Workers", "53550"},
        {"Agricultural Worker", "24090"},
        {"Supervisors of Transportation and Material Moving Workers", "54290"},
        {"Welders, Cutters, Solderers, and Brazers", "40970"},
        {"Insurance Sales Agents", "64790"},
        {"Pharmacy Technicians", "31680"},
        {"Packaging and Filling Machine Operators and Tenders", "29770"},
        {"Managers, All Other", "111230"},
        {"Network and Computer Systems Administrators", "82200"},
        {"Butchers and Other Meat, Poultry, and Fish Processing Workers", "27410"},
        {"Preschool Teachers, Except Special Education", "32500"},
        {"Sales Managers", "130400"},
        {"Hairstylist", "28790"},
        {"Diagnostic Related Technologists and Technicians", "62080"},
        {"Life, Physical, and Social Science Technicians", "47640"},
        {"Social and Human Service Assistants", "33190"},
        {"Operating Engineers and Other Construction Equipment Operators", "49110"},
        {"Hairdressers, Hairstylists, and Cosmetologists", "28770"},
        {"Other Transportation Workers", "29410"},
        {"Machine Tool Cutting Setters, Operators, and Tenders, Metal and Plastic", "34530"},
        {"Computer and Information Systems Managers", "141000"},
        {"Cleaners of Vehicles and Equipment", "23940"},
        {"Recreation Workers", "26610"},
        {"Credit Counselors and Loan Officers", "72810"},
        {"Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products", "89170"},
        {"Fire Fighting and Prevention Workers", "49690"},
        {"Industrial Machinery Mechanics", "51470"},
        {"Dental Assistants", "36920"},
        {"Physicians and Surgeons, All Other", "197700"},
        {"Clinical Laboratory Technologists and Technicians", "51810"},
        {"Securities, Commodities, and Financial Services Sales Agents", "102860"},
        {"Bill and Account Collector", "36600"},
        {"Firefighters", "49330"},
        {"Postal Service Mail Carriers", "51130"},
        {"Medical and Health Services Managers", "106070"},
        {"Electrical and Electronics Engineers", "99520"},
        {"Plant and System Operators", "58780"},
        {"Production, Planning, and Expediting Clerks", "48210"},
        {"Loan Officers", "75170"},
        {"Pharmacists", "119270"},
        {"Child, Family, and School Social Workers", "46610"},
        {"Dispatchers", "40140"},
        {"Purchasing Agents, Except Wholesale, Retail, and Farm Products", "66120"},
        {"Computer Programmers", "84360"},
        {"Claims Adjusters, Appraisers, Examiners, and Investigators", "64350"},
        {"Life Scientists", "81920"},
        {"Art Teacher", "73660"},
        {"Mechanical Engineers", "88190"},
        {"Civil Engineers", "87940"},
        {"Heating, Air Conditioning, and Refrigeration Mechanics and Installers", "47380"},
        {"Amusement and Recreation Attendant", "21360"},
        {"Electrical, Electronics, and Electromechanical Assemblers", "33570"},
        {"Teachers and Instructors, All Other, Except Substitute Teachers", "47410"},
        {"Industrial Engineers, Including Health and Safety", "87070"},
        {"Farmworkers and Laborers, Crop, Nursery, and Greenhouse", "22130"},
        {"Paralegals and Legal Assistants", "52390"},
        {"Claims Adjusters, Examiners, and Investigators", "64300"},
        {"Supervisors of Protective Service Workers", "70530"},
        {"First-Line Supervisors of Building and Grounds Cleaning and Maintenance Workers", "42680"},
        {"Administrative Services Manager", "94840"},
        {"Financial Analysts", "95320"},
        {"Data Entry and Information Processing Workers", "32840"},
        {"Physical Scientists", "85180"},
        {"Insurance Claims and Policy Processing Clerks", "39560"},
        {"Extraction Workers", "46970"},
        {"Air Transportation Worker", "87140"},
        {"Food Servers, Nonrestaurant", "23010"},
        {"Compliance Officers", "69180"},
        {"Printing Workers", "36440"},
        {"Coach", "41470"},
        {"Training and Development Specialists", "62460"},
        {"Librarians, Curators, and Archivists", "48960"},
        {"Educational, Guidance, School, and Vocational Counselors", "56490"},
        {"Bus and Truck Mechanics and Diesel Engine Specialists", "46110"},
        {"First-Line Supervisors of Non-Retail Sales Workers", "84910"},
        {"Industrial Engineers", "86990"},
        {"Woodworkers", "31300"},
        {"Hotel, Motel, and Resort Desk Clerks", "22610"},
        {"Production Workers, All Other", "31520"},
        {"Construction Managers", "97510"},
        {"Office and Administrative Support Workers, All Other", "34730"},
        {"Social Scientists and Related Workers", "78520"},
        {"Chief Executives", "185850"},
        {"Parts Salespersons", "32750"},
        {"Fitness Trainers and Aerobics Instructors", "40970"},
        {"Emergency Medical Technicians and Paramedics", "35430"},
        {"Health Teachers, Postsecondary", "104470"},
        {"Education Administrators, Elementary and Secondary School", "92940"},
        {"Radio and Telecommunications Equipment Installers and Repairers", "54420"},
        {"Helpers, Construction Trades", "29890"},
        {"Telemarketers", "26470"},
        {"Coaches and Scouts", "40050"},
        {"Line Installers and Repairers", "60160"},
        {"Media and Communication Equipment Workers", "53220"},
        {"Telecommunications Equipment Installers and Repairers, Except Line Installers", "54510"},
        {"Public Relations Specialists", "65830"},
        {"Self-Enrichment Education Teachers", "42350"},
        {"Loan Interviewers and Clerks", "39210"},
        {"Painters and Paperhangers", "40490"},
        {"Cost Estimators", "64810"},
        {"Painters, Construction and Maintenance", "40540"},
        {"Electrical and Electronic Equipment Assemblers", "33260"},
        {"Physical Therapists", "85790"},
        {"Supervisors of Personal Care and Service Workers", "39870"},
        {"Drafters", "55820"},
        {"Graphic Designers", "51640"},
        {"First-Line Supervisors of Transportation and Material-Moving Machine and Vehicle Operators", "58470"},
        {"Legal Secretaries", "46470"},
        {"Laundry and Dry-Cleaning Workers", "22660"},
        {"Food Service Managers", "53640"},
        {"Dental Hygienists", "72720"},
        {"Data Entry Keyers", "30810"},
        {"Personal Financial Advisors", "118050"},
        {"Dispatchers, Except Police, Fire, and Ambulance", "40210"},
        {"Special Education Teachers, Kindergarten and Elementary School", "58640"},
        {"Radiologic Technologists", "58520"},
        {"Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic", "33030"},
        {"Cooks, Short Order", "21940"},
        {"Marketing Managers", "140660"},
        {"Postsecondary Teachers, All Other", "71060"},
        {"Real Estate Brokers and Sales Agents", "62850"},
        {"Medical Records and Health Information Technicians", "40430"},
        {"Writers and Editors", "68090"},
        {"Crushing, Grinding, Polishing, Mixing, and Blending Workers", "35370"},
        {"Order Clerks", "34080"},
        {"Animal Care and Service Worker", "24260"},
        {"Computer Network Support Specialists", "67260"},
        {"Interviewers, Except Eligibility and Loan", "32930"},
        {"Taxi Drivers and Chauffeurs", "26070"},
        {"Heavy Vehicle and Mobile Equipment Service Technicians and Mechanics", "48180"},
        {"Architectural and Engineering Manager", "141650"},
        {"Health Specialties Teachers, Postsecondary", "114510"},
        {"Electrical Engineers", "97340"},
        {"First-Line Supervisors of Personal Service Workers", "38670"},
        {"Information and Record Clerks, All Other", "38770"},
        {"Baker", "26270"},
        {"First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand", "49670"},
        {"Property, Real Estate, and Community Association Managers", "68240"},
        {"Nonfarm Animal Caretakers", "23630"},
        {"Computer Control Programmers and Operators", "40650"},
        {"Industrial Production Managers", "103720"},
        {"Bus Drivers, Transit and Intercity", "40160"},
        {"Printing Press Operators", "37020"},
        {"First-Line Supervisors of Housekeeping and Janitorial Workers", "40060"},
        {"Payroll and Timekeeping Clerks", "42130"},
        {"Cement Masons, Concrete Finishers, and Terrazzo Workers", "42150"},
        {"Cement Masons and Concrete Finishers", "42080"},
        {"Medical and Clinical Laboratory Technologists", "61860"},
        {"Kindergarten Teachers, Except Special Education", "54510"},
        {"Medical and Clinical Laboratory Technicians", "41420"},
        {"Painting Workers", "37110"},
        {"Healthcare Social Workers", "54020"},
        {"Meat, Poultry, and Fish Cutters and Trimmers", "24810"},
        {"Producer", "85850"},
        {"Real Estate Sales Agents", "58410"},
        {"Advertising Sales Agent", "61690"},
        {"Molders and Molding Machine Setters, Operators, and Tenders, Metal and Plastic", "31720"},
        {"Computer Network Architects", "103100"},
        {"Computer-Controlled Machine Tool Operators, Metal and Plastic", "38720"},
        {"Parking Lot Attendants", "22520"},
        {"Automotive Body Repairer", "44590"},
        {"First-Line Supervisors of Law Enforcement Workers", "78950"},
        {"Installation, Maintenance, and Repair Workers, All Other", "41120"},
        {"Highway Maintenance Workers", "38200"},
        {"Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers", "21930"},
        {"Sewing Machine Operators", "24680"},
        {"File Clerks", "29900"},
        {"Instructional Coordinators", "64870"},
        {"Electrical and Electronics Engineering Technicians", "61870"},
        {"Human Resources Assistants, Except Payroll and Timekeeping", "39180"},
        {"Reservation and Transportation Ticket Agents and Travel Clerks", "36780"},
        {"Butchers and Meat Cutters", "30940"},
        {"Nurse Practitioners", "101260"},
        {"Education Administrators, Postsecondary", "102610"},
        {"Sheet Metal Workers", "49810"},
        {"Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic", "31510"},
        {"Electronics Engineers, Except Computer", "102390"},
        {"Logisticians", "77470"},
        {"Food Batchmakers", "29210"},
        {"Physical Therapist Assistants and Aides", "44590"},
        {"Tax Examiners, Collectors and Preparers, and Revenue Agents", "50410"},
        {"Librarians", "58930"},
        {"Speech-Language Pathologists", "76900"},
        {"Eligibility Interviewers, Government Programs", "43040"},
        {"Court, Municipal, and License Clerks", "38230"},
        {"Special Education Teachers, Secondary School", "62180"},
        {"Chefs and Head Cooks", "45920"},
        {"Mixing and Blending Machine Setters, Operators, and Tenders", "36410"},
        {"Mental Health Counselors", "45080"},
        {"Family and General Practitioners", "192120"},
        {"Financial Specialists, All Other", "72480"},
        {"Web Developers", "70660"},
        {"Environmental Scientists and Geoscientists", "82480"},
        {"Engineers, All Other", "98150"},
        {"Architect", "82850"},
        {"Graduate Teaching Assistants", "32510"},
        {"Helpers--Installation, Maintenance, and Repair Workers", "28530"},
        {"Woodworking Machine Setters, Operators, and Tenders", "29130"},
        {"Aircraft Mechanic", "60160"},
        {"Forming Machine Setters, Operators, and Tenders, Metal and Plastic", "36650"},
        {"Human Resources Managers", "117080"},
        {"Rail Transportation Workers", "57230"},
        {"Mobile Heavy Equipment Mechanics, Except Engines", "50080"},
        {"Flight Engineer", "119360"},
        {"Respiratory Therapists", "59640"},
        {"Protective Service Workers, All Other", "32690"},
        {"Vocational Education Teachers, Postsecondary", "54260"},
        {"Social and Community Service Managers", "69430"},
        {"Gaming Services Workers", "22730"},
        {"Psychologists", "77950"},
        {"Phlebotomists", "32770"},
        {"Dentists", "177130"},
        {"Social Sciences Teachers, Postsecondary", "84180"},
        {"Chemical Processing Machine Setters, Operators, and Tenders", "46150"},
        {"Electrical Power-Line Installers and Repairers", "65650"},
        {"Water and Wastewater Treatment Plant and System Operators", "46790"},
        {"Refuse and Recyclable Material Collectors", "36370"},
        {"Ushers, Lobby Attendants, and Ticket Takers", "21060"},
        {"Database Administrators", "84250"},
        {"Communications Equipment Operators", "30250"},
        {"Wholesale and Retail Buyers, Except Farm Products", "59270"},
        {"Mental Health and Substance Abuse Social Workers", "47190"},
        {"Postal Service Mail Sorters, Processors, and Processing Machine Operators", "50650"},
        {"Medical Scientists", "92900"},
        {"Roofers", "40630"},
        {"Automotive and Watercraft Service Attendant", "23440"},
        {"Transportation, Storage, and Distribution Managers", "95130"},
        {"Flight Attendants", "46750"},
        {"Education, Training, and Library Workers, All Other", "44380"},
        {"Tire Repairers and Changers", "26310"},
        {"Detectives and Criminal Investigators", "79620"},
        {"Telecommunications Line Installers and Repairers", "54200"},
        {"Computer, Automated Teller, and Office Machine Repairers", "38990"},
        {"Drywall Installers, Ceiling Tile Installers, and Tapers", "46760"},
        {"Clinical, Counseling, and School Psychologists", "76040"},
        {"Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic", "35380"},
        {"Broadcast and Sound Engineering Technician", "48140"},
        {"Derrick, Rotary Drill, and Service Unit Operators, Oil, Gas, and Mining", "52680"},
        {"Producers and Directors", "89670"},
        {"Medical Scientists, Except Epidemiologists", "93730"},
        {"Health Technologists and Technicians, All Other", "45730"},
        {"First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers", "46900"},
        {"Residential Advisors", "27140"},
        {"Biological Scientist", "79610"},
        {"Rehabilitation Counselors", "38040"},
        {"Merchandise Displayers and Window Trimmers", "29790"},
        {"Switchboard Operators, Including Answering Service", "28990"},
        {"First-Line Supervisors of Police and Detectives", "85810"},
        {"Surgical Technologists", "45940"},
        {"Library Assistants, Clerical", "26580"},
        {"Dentists, General", "172350"},
        {"Machine Feeders and Offbearers", "30960"},
        {"Physician Assistants", "99270"},
        {"Art Teacher", "76710"},
        {"Editors", "64910"},
        {"Operations Research Analysts", "84180"},
        {"Veterinary Technologists and Technicians", "33280"},
        {"Mail Clerks and Mail Machine Operators, Except Postal Service", "29930"},
        {"Police, Fire, and Ambulance Dispatchers", "40000"},
        {"Healthcare Support Workers, All Other", "36920"},
        {"Architectural and Civil Drafter", "53470"},
        {"Gaming Dealers", "21810"},
        {"Community and Social Service Specialists, All Other", "44370"},
        {"Library Technicians", "34200"},
        {"Cabinetmakers and Bench Carpenters", "33980"},
        {"Maintenance Workers, Machinery", "44540"},
        {"Massage Therapists", "43170"},
        {"Chemists and Materials Scientists", "79130"},
        {"Construction and Building Inspectors", "60030"},
        {"Paper Goods Machine Setters, Operators, and Tenders", "37160"},
        {"Special Education Teachers, Middle School", "60300"},
        {"Artist", "77580"},
        {"Insurance Underwriters", "72650"},
        {"Information Security Analysts", "93250"},
        {"Coating, Painting, and Spraying Machine Setters, Operators, and Tenders", "33610"},
        {"Drywall and Ceiling Tile Installers", "45510"},
        {"Models, Demonstrators, and Product Promoters", "30100"},
        {"Probation Officers and Correctional Treatment Specialists", "54080"},
        {"Math and Computer Teachers, Postsecondary", "80140"},
        {"Meeting, Convention, and Event Planners", "51200"},
        {"Environmental Scientists and Specialists, Including Health", "73930"},
        {"Substance Abuse and Behavioral Disorder Counselors", "42920"},
        {"Business Teachers, Postsecondary", "92220"},
        {"Chemists", "77860"},
        {"Sales and Related Workers, All Other", "40540"},
        {"Manicurists and Pedicurists", "23630"},
        {"Demonstrators and Product Promoters", "29720"},
        {"Airline Pilot", "136400"},
        {"Physical Therapist Assistants", "55250"},
        {"Cargo and Freight Agents", "44470"},
        {"Slaughterers and Meat Packers", "26420"},
        {"Medical, Dental, and Ophthalmic Laboratory Technicians", "37610"},
        {"Compensation, Benefits, and Job Analysis Specialists", "65100"},
        {"Structural Metal Fabricators and Fitters", "39040"},
        {"Labor Relations Specialists", "60930"},
        {"Cutting Workers", "32370"},
        {"Postal Service Clerks", "49090"},
        {"Concierge", "27030"},
        {"Career/Technical Education Teachers, Secondary School", "58170"},
        {"Water Transportation Workers", "64720"},
        {"Textile Machine Setters, Operators, and Tenders", "27640"},
        {"Religious Workers", "46020"},
        {"Computer Hardware Engineers", "114970"},
        {"English Language and Literature Teachers, Postsecondary", "71210"},
        {"Veterinary Assistants and Laboratory Animal Caretakers", "25940"},
        {"Woodworking Machine Setters, Operators, and Tenders, Except Sawing", "29090"},
        {"Carpet, Floor, and Tile Installers and Finishers", "43180"},
        {"Stonemasons", "50200"},
        {"Tool and Die Makers", "51130"},
        {"Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic", "34560"},
        {"Opticians, Dispensing", "36820"},
        {"Couriers and Messengers", "29130"},
        {"Biological Technician", "45230"},
        {"Purchasing Managers", "114130"},
        {"Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic", "34580"},
        {"Sales Engineers", "107160"},
        {"Tax Preparers", "44730"},
        {"Life, Physical, and Social Science Technicians, All Other", "48360"},
        {"Roustabouts, Oil and Gas", "38700"},
        {"Helpers--Electricians", "30000"},
        {"Procurement Clerks", "41010"},
        {"Civil Engineering Technicians", "51330"},
        {"Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders", "34030"},
        {"Credit Analysts", "79720"},
        {"Engineering Technicians, Except Drafters, All Other", "62820"},
        {"Pest Control Workers", "34080"},
        {"First-Line Supervisors of Protective Service Workers, All Other", "49540"},
        {"Psychiatric Aides", "28170"},
        {"Weighers, Measurers, Checkers, and Samplers, Recordkeeping", "30980"},
        {"Electrical and Electronics Repairers, Commercial and Industrial Equipment", "56670"},
        {"Word Processors and Typists", "38710"},
        {"Crossing Guards", "27730"},
        {"Small Engine Mechanics", "36420"},
        {"Chemical Equipment Operators and Tenders", "49640"},
        {"Aerospace Engineer", "110570"},
        {"Precision Instrument and Equipment Repairers", "48230"},
        {"Travel Agents", "38750"},
        {"Veterinarians", "99000"},
        {"Mechanical Drafters", "56610"},
        {"Education and Library Science Teachers, Postsecondary", "68560"},
        {"Secondary Education Teacher", "54060"},
        {"Chemical Technicians", "48730"},
        {"Security and Fire Alarm Systems Installers", "44860"},
        {"Funeral Service Workers", "37460"},
        {"Structural Iron and Steel Workers", "54750"},
        {"Cutting and Slicing Machine Setters, Operators, and Tenders", "33250"},
        {"Office Machine Operators, Except Computer", "30980"},
        {"Life Sciences Teachers, Postsecondary", "88240"},
        {"Fundraisers", "57170"},
        {"Audio and Video Equipment Technician", "46630"},
        {"Industrial Engineering Technicians", "56320"},
        {"Brickmason", "51750"},
        {"Diagnostic Medical Sonographers", "70880"},
        {"Service Unit Operators, Oil, Gas, and Mining", "50150"},
        {"Control and Valve Installers and Repairers", "51060"},
        {"Public Relations and Fundraising Managers", "119390"},
        {"Appraiser", "58400"},
        {"Education Teachers, Postsecondary", "68200"},
        {"Dietitians and Nutritionists", "58410"},
        {"Tax Examiners and Collectors, and Revenue Agents", "57280"},
        {"Social Workers, All Other", "57970"},
        {"Musicians, Singers, and Related Workers", "-4"},
        {"Psychiatric Technicians", "36280"},
        {"First-Line Supervisors of Fire Fighting and Prevention Workers", "74970"},
        {"Medical Transcriptionists", "35720"},
        {"Health Educators", "56690"},
        {"Brokerage Clerk", "51640"},
        {"Nursing Instructors and Teachers, Postsecondary", "73150"},
        {"Personal Care and Service Workers, All Other", "24950"},
        {"Budget Analysts", "75150"},
        {"Power Plant Operators, Distributors, and Dispatchers", "75190"},
        {"Legislators", "42530"},
        {"Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters", "29950"},
        {"Insulation Workers", "44740"},
        {"Surveyors, Cartographers, and Photogrammetrists", "62650"},
        {"Dredge, Excavating, and Loading Machine Operators", "44810"},
        {"Title Examiners, Abstractors, and Searchers", "49840"},
        {"Motor Vehicle Operators, All Other", "33430"},
        {"Mathematical Science Teachers, Postsecondary", "77290"},
        {"Surveying and Mapping Technicians", "44800"},
        {"Natural Sciences Managers", "136570"},
        {"Paving, Surfacing, and Tamping Equipment Operators", "43020"},
        {"Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders", "37590"},
        {"Orderlies", "27580"},
        {"Environmental Engineers", "88040"},
        {"Food Preparation and Serving Related Workers, All Other", "23060"},
        {"Print Binding and Finishing Workers", "32170"},
        {"Physical Sciences Teachers, Postsecondary", "89840"},
        {"Painters, Transportation Equipment", "44920"},
        {"Biological Science Teacher", "86830"},
        {"Computer Operators", "42140"},
        {"Cardiovascular Technologists and Technicians", "56100"},
        {"Interior Designers", "55510"},
        {"Actor", "-4"},
        {"Physical Therapist Aides", "27440"},
        {"Medical Equipment Preparers", "34950"},
        {"Photographers", "40280"},
        {"Judges, Magistrates, and Other Judicial Workers", "103390"},
        {"Excavating and Loading Machine and Dragline Operators", "44520"},
        {"Technical Writers", "73350"},
        {"Interpreters and Translators", "48360"},
        {"New Accounts Clerks", "35820"},
        {"Internists, General", "196520"},
        {"Mechanical Engineering Technicians", "56390"},
        {"Sawing Machine Setters, Operators, and Tenders, Wood", "29190"},
        {"Pressers, Textile, Garment, and Related Materials", "21640"},
        {"Clergy", "48150"},
        {"Community Health Workers", "40150"},
        {"Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders", "41210"},
        {"Television, Video, and Motion Picture Camera Operators and Editors", "71500"},
        {"Education Administrators, Preschool and Childcare Center/Program", "52760"},
        {"Baggage Porter", "24430"},
        {"Crane and Tower Operators", "54560"},
        {"Electromechanical Equipment Assemblers", "35140"},
        {"News Analysts, Reporters and Correspondents", "50970"},
        {"Food Processing Workers, All Other", "25220"},
        {"Forest, Conservation, and Logging Workers", "36470"},
        {"Legal Support Workers, All Other", "64530"},
        {"Engineering and Architecture Teachers, Postsecondary", "101040"},
        {"Floral Designers", "27010"},
        {"Glaziers", "45420"},
        {"Financial Examiners", "88310"},
        {"Locomotive Engineers and Operators", "57980"},
        {"Writers and Authors", "69130"},
        {"Surveyors", "61880"},
        {"Aircraft Assembler", "51040"},
        {"Law, Criminal Justice, and Social Work Teachers, Postsecondary", "89470"},
        {"Hazardous Materials Removal Workers", "44150"},
        {"First-Line Supervisors of Correctional Officers", "62770"},
        {"Control and Valve Installers and Repairers, Except Mechanical Door", "55760"},
        {"Railroad Conductors and Yardmasters", "56760"},
        {"Petroleum Pump System Operators, Refinery Operators, and Gaugers", "66020"},
        {"Credit Authorizers, Checkers, and Clerks", "37920"},
        {"Transportation Security Screeners", "40050"},
        {"Surgeons", "247520"},
        {"Medical Equipment Repairers", "49400"},
        {"Reporters and Correspondents", "46560"},
        {"Pipelayers", "41910"},
        {"Skincare Specialists", "35300"},
        {"Tree Trimmers and Pruners", "36030"},
        {"Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic", "38080"},
        {"Millwrights", "52650"},
        {"Commercial Pilots", "84510"},
        {"Healthcare Practitioners and Technical Workers, All Other", "56400"},
        {"Nurse Anesthetists", "160250"},
        {"Ophthalmic Medical Technicians", "36690"},
        {"Real Estate Brokers", "80210"},
        {"Tour and Travel Guides", "27640"},
        {"Molders, Shapers, and Casters, Except Metal and Plastic", "31690"},
        {"Engine and Other Machine Assemblers", "41750"},
        {"Logging Workers", "37640"},
        {"Special Education Teachers, All Other", "57670"},
        {"Announcers", "45170"},
        {"Psychology Teachers, Postsecondary", "79370"},
        {"Pharmacy Aides", "27460"},
        {"Transportation Workers, All Other", "38520"},
        {"Helpers--Carpenters", "29200"},
        {"Dental Laboratory Technicians", "40520"},
        {"Power Plant Operators", "71070"},
        {"Locomotive Engineers", "59360"},
        {"Engineering Teachers, Postsecondary", "104220"},
        {"Musicians and Singers", "-4"},
        {"Farm Equipment Mechanics and Service Technicians", "38510"},
        {"Ship and Boat Captains and Operators", "79000"},
        {"Tour Guides and Escorts", "26920"},
        {"Health Diagnosing and Treating Practitioners, All Other", "85120"},
        {"Plating and Coating Machine Setters, Operators, and Tenders, Metal and Plastic", "32930"},
        {"Lodging Managers", "57810"},
        {"Urban and Regional Planners", "70680"},
        {"Prepress Technicians and Workers", "40060"},
        {"Optometrists", "115750"},
        {"Funeral Attendants", "25840"},
        {"Graders and Sorters, Agricultural Products", "23260"},
        {"Chemical Plant and System Operators", "59070"},
        {"Meter Readers, Utilities", "40900"},
        {"Tile and Marble Setters", "44010"},
        {"Financial Clerks, All Other", "42270"},
        {"Art Director", "101990"},
        {"Food Cooking Machine Operators and Tenders", "29430"},
        {"Stationary Engineers and Boiler Operators", "60480"},
        {"Petroleum Engineers", "149590"},
        {"Environmental Science and Protection Technicians, Including Health", "46540"},
        {"Social Scientists and Related Workers, All Other", "80650"},
        {"Home Appliance Repairers", "38820"},
        {"Computer Science Teachers, Postsecondary", "84700"},
        {"Farmworkers, Farm, Ranch, and Aquacultural Animals", "26160"},
        {"Magnetic Resonance Imaging Technologists", "68340"},
        {"Captains, Mates, and Pilots of Water Vessels", "83150"},
        {"Conveyor Operators and Tenders", "35100"},
        {"Construction and Related Workers, All Other", "39500"},
        {"Coin, Vending, and Amusement Machine Servicers and Repairers", "34260"},
        {"Chemical Engineers", "103960"},
        {"Chiropractors", "78370"},
        {"Marriage and Family Therapists", "53520"},
        {"Education Administrators, All Other", "82970"},
        {"Geoscientists, Except Hydrologists and Geographers", "105720"},
        {"Rolling Machine Setters, Operators, and Tenders, Metal and Plastic", "41200"},
        {"Agricultural and Food Scientist", "69230"},
        {"Outdoor Power Equipment and Other Small Engine Mechanics", "34520"},
        {"Concierges", "30870"},
        {"Training and Development Managers", "111680"},
        {"Commercial and Industrial Designers", "69820"},
        {"Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders", "35560"},
        {"Air Traffic Controller Specialist", "102580"},
        {"Biochemist", "93390"},
        {"Sailors and Marine Oilers", "42910"},
        {"Credit Counselors", "49310"},
        {"Private Detectives and Investigators", "52840"},
        {"Radio and Television Announcers", "46410"},
        {"Pumping Station Operators", "48570"},
        {"First-Line Supervisors of Gaming Workers", "46940"},
        {"Multimedia Artists and Animators", "70300"},
        {"Upholsterers", "33550"},
        {"Foreign Language and Literature Teachers, Postsecondary", "69520"},
        {"Statisticians", "84440"},
        {"Forest and Conservation Technicians", "38260"},
        {"Metal Furnace Operators, Tenders, Pourers, and Casters", "40390"},
        {"Advertising Manager", "113610"},
        {"Insulation Workers, Mechanical", "49970"},
        {"Special Education Teachers, Preschool", "58210"},
        {"Anesthesiologist", "258100"},
        {"Electrical and Electronics Drafters", "62890"},
        {"Communications Teachers, Postsecondary", "70290"},
        {"Judges, Magistrate Judges, and Magistrates", "116100"},
        {"Dietetic Technicians", "29170"},
        {"Conservation Scientists and Foresters", "62860"},
        {"Pediatricians, General", "183180"},
        {"Broadcast Technician", "44050"},
        {"Grinding and Polishing Workers, Hand", "30370"},
        {"Curator", "51750"},
        {"Social Science Research Assistants", "45760"},
        {"Ophthalmic Laboratory Technicians", "32970"},
        {"Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders", "27580"},
        {"Film and Video Editors", "80300"},
        {"Logging Equipment Operators", "36930"},
        {"Agricultural Equipment Operator", "29380"},
        {"Septic Tank Servicers and Sewer Pipe Cleaners", "37880"},
        {"Materials Engineers", "94690"},
        {"Tailors, Dressmakers, and Sewers", "27690"},
        {"Electronic Home Entertainment Equipment Installers and Repairers", "39670"},
        {"Counselors, All Other", "47950"},
        {"Transportation Inspectors", "72220"},
        {"Insulation Workers, Floor, Ceiling, and Wall", "38810"},
        {"Carpet Installers", "43210"},
        {"Computer Numerically Controlled Machine Tool Programmers, Metal and Plastic", "51630"},
        {"Computer and Information Research Scientists", "115580"},
        {"Morticians, Undertakers, and Funeral Directors", "52990"},
        {"Jewelers and Precious Stone and Metal Workers", "42380"},
        {"Rotary Drill Operators, Oil and Gas", "60380"},
        {"Health and Safety Engineers, Except Mining Safety Engineers and Inspectors", "87810"},
        {"Semiconductor Processors", "37600"},
        {"Pesticide Handlers, Sprayers, and Applicators, Vegetation", "34570"},
        {"Psychiatrists", "193680"},
        {"Photographic Process Workers and Processing Machine Operators", "30720"},
        {"Philosophy and Religion Teachers, Postsecondary", "75140"},
        {"History Teachers, Postsecondary", "76670"},
        {"Athletic Trainer", "46940"},
        {"Air Traffic Controller", "118740"},
        {"Electrical and Electronics Repairers, Powerhouse, Substation, and Relay", "72450"},
        {"Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters", "32090"},
        {"Helpers--Extraction Workers", "37080"},
        {"Gaming Change Persons and Booth Cashiers", "24620"},
        {"Riggers", "47770"},
        {"Gaming Supervisors", "50130"},
        {"Textile Knitting and Weaving Machine Setters, Operators, and Tenders", "28150"},
        {"Plasterers and Stucco Masons", "42070"},
        {"Media and Communication Workers, All Other", "52200"},
        {"Metal Workers and Plastic Workers, All Other", "35910"},
        {"Material Moving Workers, All Other", "37060"},
        {"Music Directors and Composers", "59040"},
        {"Chemistry Teachers, Postsecondary", "86070"},
        {"Rail Car Repairers", "54130"},
        {"Microbiologists", "76230"},
        {"Fence Erectors", "34840"},
        {"Physical Scientists, All Other", "98240"},
        {"Elevator Installers and Repairers", "77350"},
        {"Biomedical Engineer", "91230"},
        {"Fiberglass Laminators and Fabricators", "30760"},
        {"Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic", "38420"},
        {"Motorboat Mechanics and Service Technicians", "39500"},
        {"Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders", "30320"},
        {"Directors, Religious Activities and Education", "45160"},
        {"Agricultural and Food Science Technician", "39000"},
        {"Conservation Scientists", "63800"},
        {"Obstetricians and Gynecologists", "222400"},
        {"Metal-Refining Furnace Operators and Tenders", "42790"},
        {"Camera Operators, Television, Video, and Motion Picture", "59360"},
        {"Reinforcing Iron and Rebar Workers", "54030"},
        {"Tailors, Dressmakers, and Custom Sewers", "28630"},
        {"Ambulance Driver", "25470"},
        {"Mining Machine Operators", "50530"},
        {"Landscape Architects", "68600"},
        {"Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers", "34190"},
        {"Actuary", "110560"},
        {"Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic", "39620"},
        {"Nuclear Medicine Technologists", "74990"},
        {"Forging Machine Setters, Operators, and Tenders, Metal and Plastic", "36910"},
        {"Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders", "36970"},
        {"Earth Drillers, Except Oil and Gas", "51840"},
        {"Derrick Operators, Oil and Gas", "50710"},
        {"Economists", "109230"},
        {"First-Line Supervisors of Farming, Fishing, and Forestry Workers", "48290"},
        {"Fashion Designers", "73180"},
        {"Railroad Brake, Signal, and Switch Operators", "53990"},
        {"Helpers, Construction Trades, All Other", "30500"},
        {"Umpires, Referees, and Other Sports Officials", "33990"},
        {"Recreation and Fitness Studies Teachers, Postsecondary", "66090"},
        {"Mechanical Door Repairers", "39900"},
        {"Electric Motor, Power Tool, and Related Repairers", "43760"},
        {"Zoologists and Wildlife Biologists", "64230"},
        {"Recreational Therapists", "47790"},
        {"Locksmiths and Safe Repairers", "41270"},
        {"Bailiff", "44900"},
        {"Tire Builders", "40230"},
        {"Court Reporters", "54720"},
        {"Media and Communication Equipment Workers, All Other", "70920"},
        {"Gaming Cage Workers", "27780"},
        {"Tapers", "53080"},
        {"Political Science Teachers, Postsecondary", "88680"},
        {"Locker Room, Coatroom, and Dressing Room Attendants", "23990"},
        {"Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders", "29910"},
        {"Physicist", "117660"},
        {"Adhesive Bonding Machine Operator", "33750"},
        {"Environmental Engineering Technicians", "51170"},
        {"Avionics Technician", "60200"},
        {"Automotive Glass Installer", "35210"},
        {"Radiation Therapists", "84460"},
        {"Grounds Maintenance Workers, All Other", "33340"},
        {"Nuclear Engineers", "106060"},
        {"Geological and Petroleum Technicians", "60710"},
        {"Gas Plant Operators", "65830"},
        {"Textile, Apparel, and Furnishings Workers, All Other", "29720"},
        {"Building Cleaning Workers, All Other", "30200"},
        {"Furniture Finishers", "30920"},
        {"Law Teachers, Postsecondary", "126230"},
        {"Boilermaker", "60660"},
        {"Sociology Teachers, Postsecondary", "76750"},
        {"Painting, Coating, and Decorating Workers", "31210"},
        {"Compensation and Benefits Managers", "121630"},
        {"Motorcycle Mechanics", "36240"},
        {"Cutters and Trimmers, Hand", "28850"},
        {"Transportation Attendants, Except Flight Attendants", "30540"},
        {"Physicists", "118500"},
        {"Drafters, All Other", "53660"},
        {"Insurance Appraisers, Auto Damage", "65300"},
        {"Shampooers", "20350"},
        {"Cooks, All Other", "28240"},
        {"Dancers and Choreographers", "42410"},
        {"Entertainment Attendants and Related Workers, All Other", "24110"},
        {"Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic", "37660"},
        {"Postmasters and Mail Superintendents", "70540"},
        {"Electro-Mechanical Technicians", "56320"},
        {"Textile Cutting Machine Setters, Operators, and Tenders", "26950"},
        {"Agricultural Inspector", "43810"},
        {"Food Scientists and Technologists", "72030"},
        {"Medical Appliance Technicians", "39020"},
        {"Soil and Plant Scientists", "65980"},
        {"Administrative Law Judges, Adjudicators, and Hearing Officers", "93140"},
        {"Entertainers and Performers, Sports and Related Workers, All Other", "-4"},
        {"Criminal Justice and Law Enforcement Teachers, Postsecondary", "64460"},
        {"Rail-Track Laying and Maintenance Equipment Operators", "51340"},
        {"Coil Winders, Tapers, and Finishers", "32990"},
        {"Barber", "29140"},
        {"Physics Teachers, Postsecondary", "93950"},
        {"Electrical and Electronics Installers and Repairers, Transportation Equipment", "59080"},
        {"Radio, Cellular, and Tower Equipment Installers and Repairers", "52940"},
        {"Forensic Science Technicians", "60090"},
        {"Fire Inspectors", "58020"},
        {"Sound Engineering Technicians", "63340"},
        {"Survey Researchers", "59340"},
        {"Economics Teachers, Postsecondary", "106980"},
        {"Statistical Assistants", "44220"},
        {"Pump Operators, Except Wellhead Pumpers", "46200"},
        {"Desktop Publishers", "43900"},
        {"Agent", "95810"},
        {"Stonemasons", "42970"},
        {"Animal Control Worker", "35330"},
        {"Career/Technical Education Teachers, Middle School", "58480"},
        {"Aerospace Engineering Technician", "68620"},
        {"Foundry Mold and Coremakers", "33930"},
        {"Wellhead Pumpers", "48180"},
        {"Judicial Law Clerks", "59910"},
        {"Subway and Streetcar Operators", "60580"},
        {"Bicycle Repairer", "27900"},
        {"Electronic Equipment Installers and Repairers, Motor Vehicles", "33500"},
        {"Psychologists, All Other", "93050"},
        {"Gaming and Sports Book Writers and Runners", "26170"},
        {"Fire Inspectors and Investigators", "59800"},
        {"Gaming Service Workers, All Other", "26380"},
        {"Fine Artists, Including Painters, Sculptors, and Illustrators", "54170"},
        {"Buyers and Purchasing Agents, Farm Products", "62280"},
        {"Precision Instrument and Equipment Repairers, All Other", "54110"},
        {"Audiologist", "77420"},
        {"Cartographers and Photogrammetrists", "65410"},
        {"Recreational Vehicle Service Technicians", "37380"},
        {"Tank Car, Truck, and Ship Loaders", "41010"},
        {"Set and Exhibit Designers", "54920"},
        {"Curators", "56990"},
        {"Social Work Teachers, Postsecondary", "69030"},
        {"Animal Trainer", "33600"},
        {"Athlete", "80490"},
        {"Textile Bleaching and Dyeing Machine Operators and Tenders", "27660"},
        {"Plant and System Operators, All Other", "55530"},
        {"Power Distributors and Dispatchers", "80400"},
        {"Shoe and Leather Workers", "25570"},
        {"Social Sciences Teachers, Postsecondary, All Other", "79820"},
        {"Continuous Mining Machine Operators", "50660"},
        {"Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons", "27690"},
        {"Space Sciences Teacher", "92540"},
        {"Therapists, All Other", "59210"},
        {"Helpers--Roofers", "27820"},
        {"Proofreaders and Copy Markers", "37690"},
        {"Museum Technicians and Conservators", "44880"},
        {"Layout Workers, Metal and Plastic", "46430"},
        {"Gaming Surveillance Officers and Gaming Investigators", "33880"},
        {"Model Makers and Patternmakers, Metal and Plastic", "45620"},
        {"Atmospheric and Space Scientist", "90210"},
        {"Tool Grinders, Filers, and Sharpeners", "37590"},
        {"Audio-Visual and Multimedia Collections Specialist", "48220"},
        {"Dancers", "-4"},
        {"Respiratory Therapy Technicians", "49720"},
        {"Ship Engineers", "78970"},
        {"Emergency Management Directors", "73750"},
        {"Floor Layers, Except Carpet, Wood, and Hard Tiles", "42520"},
        {"Telephone Operators", "40820"},
        {"Agricultural Sciences Teacher", "95280"},
        {"Pourers and Casters, Metal", "35390"},
        {"Podiatrists", "136180"},
        {"Etchers and Engravers", "31880"},
        {"Area, Ethnic, and Cultural Studies Teacher", "81700"},
        {"Life Scientists, All Other", "79870"},
        {"Farm and Home Management Advisors", "51820"},
        {"Parking Enforcement Workers", "38280"},
        {"Foresters", "60650"},
        {"Funeral Service Managers", "84470"},
        {"Signal and Track Switch Repairers", "62650"},
        {"Shoe and Leather Workers and Repairers", "25570"},
        {"Mining and Geological Engineers, Including Mining Safety Engineers", "107880"},
        {"Public Address System and Other Announcers", "40440"},
        {"Cooling and Freezing Equipment Operators and Tenders", "31490"},
        {"Airfield Operations Specialist", "55400"},
        {"Religious Workers, All Other", "35160"},
        {"Musical Instrument Repairers and Tuners", "38590"},
        {"Slot Supervisors", "37550"},
        {"Marine Engineers and Naval Architects", "100090"},
        {"Explosives Workers, Ordnance Handling Experts, and Blasters", "52580"},
        {"Door-to-Door Sales Workers, News and Street Vendors, and Related Workers", "26160"},
        {"Nurse Midwives", "93610"},
        {"Architecture Teacher", "84880"},
        {"Correspondence Clerks", "36340"},
        {"Orthotists and Prosthetists", "69960"},
        {"Anthropologist", "64290"},
        {"Nuclear Power Reactor Operators", "88820"},
        {"Sewers, Hand", "24980"},
        {"Woodworkers, All Other", "32130"},
        {"Forest and Conservation Workers", "29860"},
        {"Solar Photovoltaic Installers", "40070"},
        {"Materials Scientists", "94940"},
        {"Aircraft Cargo Handling Supervisor", "48870"},
        {"Traffic Technicians", "47660"},
        {"Mine Cutting and Channeling Machine Operators", "50720"},
        {"Exercise Physiologists", "49740"},
        {"Designers, All Other", "62220"},
        {"Hydrologists", "83440"},
        {"Nuclear Technicians", "78850"},
        {"Arbitrator", "69060"},
        {"Model Makers, Metal and Plastic", "48210"},
        {"Costume Attendants", "52870"},
        {"Anthropology Teacher", "85440"},
        {"Hearing Aid Specialists", "52850"},
        {"Fallers", "41750"},
        {"Fish and Game Wardens", "54970"},
        {"Motion Picture Projectionists", "24540"},
        {"Dentists, All Other Specialists", "171040"},
        {"Environmental Science Teachers, Postsecondary", "88570"},
        {"Archivist", "53880"},
        {"Epidemiologists", "76900"},
        {"Orthodontists", "221390"},
        {"Extraction Workers, All Other", "49140"},
        {"Craft Artists", "35710"},
        {"Roof Bolters, Mining", "55500"},
        {"Fabric and Apparel Patternmakers", "49040"},
        {"Choreographers", "51560"},
        {"Oral and Maxillofacial Surgeons", "233900"},
        {"Library Science Teachers, Postsecondary", "73030"},
        {"Broadcast News Analyst", "89240"},
        {"Floor Sanders and Finishers", "38160"},
        {"Rail Transportation Workers, All Other", "58760"},
        {"Models", "37240"},
        {"Rail Yard Engineers, Dinkey Operators, and Hostlers", "47600"},
        {"Farmers, Ranchers, and Other Agricultural Managers", "69880"},
        {"Geography Teachers, Postsecondary", "79690"},
        {"Gas Compressor and Gas Pumping Station Operators", "57510"},
        {"Patternmakers, Metal and Plastic", "41500"},
        {"Gaming Managers", "77770"},
        {"Wind Turbine Service Technicians", "53030"},
        {"Political Scientists", "103210"},
        {"Rock Splitters, Quarry", "34870"},
        {"Transit and Railroad Police", "62090"},
        {"Embalmers", "41490"},
        {"Pile-Driver Operators", "55150"},
        {"Home Economics Teachers, Postsecondary", "69090"},
        {"Manufactured Building and Mobile Home Installers", "33150"},
        {"Motorboat Operators", "41350"},
        {"Camera and Photographic Equipment Repairers", "42510"},
        {"Commercial Divers", "54640"},
        {"Terrazzo Workers and Finishers", "46050"},
        {"Shoe Machine Operators and Tenders", "25560"},
        {"Loading Machine Operators, Underground Mining", "49740"},
        {"Bridge and Lock Tender", "45980"},
        {"Mathematicians", "112560"},
        {"Makeup Artists, Theatrical and Performance", "66560"},
        {"Paperhangers", "36610"},
        {"Historians", "61120"},
        {"Hoist and Winch Operators", "50680"},
        {"Logging Workers, All Other", "36210"},
        {"Travel Guides", "36920"},
        {"Log Graders and Scalers", "37420"},
        {"Sociologists", "82100"},
        {"Genetic Counselors", "74570"},
        {"Animal Scientist", "71830"},
        {"Agricultural Engineer", "78490"},
        {"Mine Shuttle Car Operators", "55120"},
        {"Watch Repairers", "37110"},
        {"Model Makers and Patternmakers, Wood", "39840"},
        {"Mining Machine Operators, All Other", "49270"},
        {"Communications Equipment Operators, All Other", "41990"},
        {"Dredge Operators", "44040"},
        {"Astronomers", "110220"},
        {"Forestry and Conservation Science Teachers, Postsecondary", "91030"},
        {"Forest Fire Inspectors and Prevention Specialists", "44740"},
        {"Locomotive Firers", "54540"},
        {"Refractory Materials Repairers, Except Brickmasons", "48920"},
        {"Geographers", "74920"},
        {"Segmental Pavers", "31820"},
        {"Farm Labor Contractors", "43920"},
        {"Timing Device Assemblers and Adjusters", "41510"},
        {"Model Makers, Wood", "38330"},
        {"Animal Breeder", "44650"},
        {"Patternmakers, Wood", "41550"},
        {"Industrial-Organizational Psychologists", "92320"},
        {"Radio Operators", "47200"},
        {"Mathematical Technicians", "53630"},
        {"Prosthodontists", "161020"},
        {"Fishing and Hunting Workers", "30370"},
        {"Fabric Menders, Except Garment", "25840"},
        {"Fishers and Related Fishing Workers", "29970"},
        {"Cooks, Private Household", "37680"}
    };
}
