package model;

import util.Util;

/**
 * Created by SStrombe on 6/11/16.
 */
public class Profession {
    public static int INDEX_PROFESSION_TITLE = 0;
    public static int INDEX_PROFESSION_SALARY = 1;

    public static String[][] professions = new String[][] {
            {"Cooks, Fast Food","19610"},
            {"Combined Food Preparation and Serving Workers, Including Fast Food","19710"},
            {"Fast Food and Counter Workers","19820"},
            {"Shampooers","20350"},
            {"Dishwashers","20360"},
            {"Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop","20530"},
            {"Counter Attendants, Cafeteria, Food Concession, and Coffee Shop","20590"},
            {"Other Food Preparation and Serving Related Workers","20830"},
            {"Cashiers","20990"},
            {"Cashiers","21010"},
            {"Ushers, Lobby Attendants, and Ticket Takers","21060"},
            {"Amusement and Recreation Attendant","21360"},
            {"Dining Room and Cafeteria Attendants and Bartender Helpers","21400"},
            {"Food and Beverage Serving Workers","21430"},
            {"Pressers, Textile, Garment, and Related Materials","21640"},
            {"Personal Care Aides","21790"},
            {"Gaming Dealers","21810"},
            {"Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers","21930"},
            {"Cooks, Short Order","21940"},
            {"Food Preparation Workers","22050"},
            {"Farmworkers and Laborers, Crop, Nursery, and Greenhouse","22130"},
            {"Entertainment Attendants and Related Workers","22140"},
            {"Childcare Workers","22310"},
            {"Parking Lot Attendants","22520"},
            {"Hotel, Motel, and Resort Desk Clerks","22610"},
            {"Laundry and Dry-Cleaning Workers","22660"},
            {"Gaming Services Workers","22730"},
            {"Home Health Aides","22870"},
            {"Cooks and Food Preparation Workers","22990"},
            {"Maids and Housekeeping Cleaners","22990"},
            {"Food Servers, Nonrestaurant","23010"},
            {"Waiters and Waitresses","23020"},
            {"Food Preparation and Serving Related Workers, All Other","23060"},
            {"Graders and Sorters, Agricultural Products","23260"},
            {"Cooks","23350"},
            {"Automotive and Watercraft Service Attendant","23440"},
            {"Nonfarm Animal Caretakers","23630"},
            {"Manicurists and Pedicurists","23630"},
            {"Packers and Packagers, Hand","23710"},
            {"Cleaners of Vehicles and Equipment","23940"},
            {"Locker Room, Coatroom, and Dressing Room Attendants","23990"},
            {"Agricultural Worker","24090"},
            {"Bartender","24110"},
            {"Entertainment Attendants and Related Workers, All Other","24110"},
            {"Animal Care and Service Worker","24260"},
            {"Cooks, Restaurant","24430"},
            {"Baggage Porter","24430"},
            {"Other Personal Care and Service Workers","24480"},
            {"Retail Sales Workers","24490"},
            {"Motion Picture Projectionists","24540"},
            {"Gaming Change Persons and Booth Cashiers","24620"},
            {"Sewing Machine Operators","24680"},
            {"Meat, Poultry, and Fish Cutters and Trimmers","24810"},
            {"Personal Care and Service Workers, All Other","24950"},
            {"Sewers, Hand","24980"},
            {"Food Processing Workers, All Other","25220"},
            {"Building Cleaning Workers","25240"},
            {"Textile, Apparel, and Furnishings Workers","25420"},
            {"Building Cleaning and Pest Control Workers","25440"},
            {"Ambulance Driver","25470"},
            {"Nursing, Psychiatric, and Home Health Aides","25500"},
            {"Cooks, Institution and Cafeteria","25560"},
            {"Shoe Machine Operators and Tenders","25560"},
            {"Shoe and Leather Workers","25570"},
            {"Shoe and Leather Workers and Repairers","25570"},
            {"Funeral Attendants","25840"},
            {"Fabric Menders, Except Garment","25840"},
            {"Stock Clerks and Order Fillers","25940"},
            {"Veterinary Assistants and Laboratory Animal Caretakers","25940"},
            {"Helpers--Production Workers","26010"},
            {"Taxi Drivers and Chauffeurs","26070"},
            {"Farmworkers, Farm, Ranch, and Aquacultural Animals","26160"},
            {"Door-to-Door Sales Workers, News and Street Vendors, and Related Workers","26160"},
            {"Gaming and Sports Book Writers and Runners","26170"},
            {"Janitors and Cleaners, Except Maids and Housekeeping Cleaners","26180"},
            {"Baker","26270"},
            {"Tire Repairers and Changers","26310"},
            {"Retail Salespersons","26340"},
            {"Gaming Service Workers, All Other","26380"},
            {"Slaughterers and Meat Packers","26420"},
            {"Telemarketers","26470"},
            {"Teacher Assistants","26550"},
            {"Library Assistants, Clerical","26580"},
            {"Recreation Workers","26610"},
            {"Laborers and Material Movers, Hand","26760"},
            {"Nursing Assistants","26820"},
            {"Tour Guides and Escorts","26920"},
            {"Textile Cutting Machine Setters, Operators, and Tenders","26950"},
            {"Floral Designers","27010"},
            {"Concierge","27030"},
            {"Residential Advisors","27140"},
            {"Tellers","27260"},
            {"Butchers and Other Meat, Poultry, and Fish Processing Workers","27410"},
            {"Physical Therapist Aides","27440"},
            {"Landscaping and Groundskeeping Workers","27460"},
            {"Pharmacy Aides","27460"},
            {"Food Processing Workers","27500"},
            {"Orderlies","27580"},
            {"Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders","27580"},
            {"Textile Machine Setters, Operators, and Tenders","27640"},
            {"Tour and Travel Guides","27640"},
            {"Textile Bleaching and Dyeing Machine Operators and Tenders","27660"},
            {"Tailors, Dressmakers, and Sewers","27690"},
            {"Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons","27690"},
            {"Crossing Guards","27730"},
            {"Gaming Cage Workers","27780"},
            {"Helpers--Roofers","27820"},
            {"Laborers and Freight, Stock, and Material Movers, Hand","27840"},
            {"Driver/Sales Workers","27890"},
            {"Bicycle Repairer","27900"},
            {"Grounds Maintenance Workers","28090"},
            {"Textile Knitting and Weaving Machine Setters, Operators, and Tenders","28150"},
            {"Psychiatric Aides","28170"},
            {"Counter and Rental Clerks","28210"},
            {"Cooks, All Other","28240"},
            {"Personal Appearance Workers","28420"},
            {"Receptionists and Information Clerks","28430"},
            {"Security Guards","28460"},
            {"Security Guards and Gaming Surveillance Officers","28510"},
            {"Helpers--Installation, Maintenance, and Repair Workers","28530"},
            {"Tailors, Dressmakers, and Custom Sewers","28630"},
            {"Material Moving Workers","28710"},
            {"Hairdressers, Hairstylists, and Cosmetologists","28770"},
            {"Hairstylist","28790"},
            {"Cutters and Trimmers, Hand","28850"},
            {"Switchboard Operators, Including Answering Service","28990"},
            {"Other Protective Service Workers","29050"},
            {"Woodworking Machine Setters, Operators, and Tenders, Except Sawing","29090"},
            {"Woodworking Machine Setters, Operators, and Tenders","29130"},
            {"Couriers and Messengers","29130"},
            {"Barber","29140"},
            {"Dietetic Technicians","29170"},
            {"Sawing Machine Setters, Operators, and Tenders, Wood","29190"},
            {"Helpers--Carpenters","29200"},
            {"Food Batchmakers","29210"},
            {"Agricultural Equipment Operator","29380"},
            {"Other Transportation Workers","29410"},
            {"Food Cooking Machine Operators and Tenders","29430"},
            {"Substitute Teachers","29630"},
            {"Demonstrators and Product Promoters","29720"},
            {"Textile, Apparel, and Furnishings Workers, All Other","29720"},
            {"Packaging and Filling Machine Operators and Tenders","29770"},
            {"Counter and Rental Clerks and Parts Salespersons","29790"},
            {"Merchandise Displayers and Window Trimmers","29790"},
            {"Forest and Conservation Workers","29860"},
            {"Helpers, Construction Trades","29890"},
            {"File Clerks","29900"},
            {"Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders","29910"},
            {"Mail Clerks and Mail Machine Operators, Except Postal Service","29930"},
            {"Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters","29950"},
            {"Fishers and Related Fishing Workers","29970"},
            {"Helpers--Electricians","30000"},
            {"Models, Demonstrators, and Product Promoters","30100"},
            {"Building Cleaning Workers, All Other","30200"},
            {"Communications Equipment Operators","30250"},
            {"Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders","30320"},
            {"Grinding and Polishing Workers, Hand","30370"},
            {"Fishing and Hunting Workers","30370"},
            {"Helpers, Construction Trades, All Other","30500"},
            {"Transportation Attendants, Except Flight Attendants","30540"},
            {"Bus Drivers, School or Special Client","30580"},
            {"Photographic Process Workers and Processing Machine Operators","30720"},
            {"Fiberglass Laminators and Fabricators","30760"},
            {"Data Entry Keyers","30810"},
            {"Concierges","30870"},
            {"Furniture Finishers","30920"},
            {"Butchers and Meat Cutters","30940"},
            {"Machine Feeders and Offbearers","30960"},
            {"Weighers, Measurers, Checkers, and Samplers, Recordkeeping","30980"},
            {"Office Machine Operators, Except Computer","30980"},
            {"Painting, Coating, and Decorating Workers","31210"},
            {"Woodworkers","31300"},
            {"Cooling and Freezing Equipment Operators and Tenders","31490"},
            {"Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic","31510"},
            {"Production Workers, All Other","31520"},
            {"Team Assemblers","31560"},
            {"Pharmacy Technicians","31680"},
            {"Molders, Shapers, and Casters, Except Metal and Plastic","31690"},
            {"Molders and Molding Machine Setters, Operators, and Tenders, Metal and Plastic","31720"},
            {"Segmental Pavers","31820"},
            {"Etchers and Engravers","31880"},
            {"Office Clerks, General","31890"},
            {"Medical Assistants","31910"},
            {"Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters","32090"},
            {"Woodworkers, All Other","32130"},
            {"Print Binding and Finishing Workers","32170"},
            {"Shipping, Receiving, and Traffic Clerks","32350"},
            {"Cutting Workers","32370"},
            {"Preschool Teachers, Except Special Education","32500"},
            {"Graduate Teaching Assistants","32510"},
            {"Recreation and Fitness Workers","32560"},
            {"Assembler","32670"},
            {"Protective Service Workers, All Other","32690"},
            {"Parts Salespersons","32750"},
            {"Phlebotomists","32770"},
            {"Other Office and Administrative Support Workers","32800"},
            {"Data Entry and Information Processing Workers","32840"},
            {"Interviewers, Except Eligibility and Loan","32930"},
            {"Plating and Coating Machine Setters, Operators, and Tenders, Metal and Plastic","32930"},
            {"Ophthalmic Laboratory Technicians","32970"},
            {"Bus Drivers","32980"},
            {"Coil Winders, Tapers, and Finishers","32990"},
            {"Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic","33030"},
            {"Manufactured Building and Mobile Home Installers","33150"},
            {"Social and Human Service Assistants","33190"},
            {"Cutting and Slicing Machine Setters, Operators, and Tenders","33250"},
            {"Electrical and Electronic Equipment Assemblers","33260"},
            {"Veterinary Technologists and Technicians","33280"},
            {"First-Line Supervisors of Food Preparation and Serving Workers","33330"},
            {"Grounds Maintenance Workers, All Other","33340"},
            {"Motor Vehicle Operators, All Other","33430"},
            {"Electronic Equipment Installers and Repairers, Motor Vehicles","33500"},
            {"Upholsterers","33550"},
            {"Electrical, Electronics, and Electromechanical Assemblers","33570"},
            {"Animal Trainer","33600"},
            {"Information and Record Clerks","33610"},
            {"Material Recording, Scheduling, Dispatching, and Distributing Workers","33610"},
            {"Coating, Painting, and Spraying Machine Setters, Operators, and Tenders","33610"},
            {"Adhesive Bonding Machine Operator","33750"},
            {"Gaming Surveillance Officers and Gaming Investigators","33880"},
            {"Foundry Mold and Coremakers","33930"},
            {"Cabinetmakers and Bench Carpenters","33980"},
            {"Umpires, Referees, and Other Sports Officials","33990"},
            {"Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders","34030"},
            {"Light Truck or Delivery Services Drivers","34080"},
            {"Order Clerks","34080"},
            {"Pest Control Workers","34080"},
            {"Industrial Truck and Tractor Operators","34090"},
            {"Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers","34190"},
            {"Library Technicians","34200"},
            {"Coin, Vending, and Amusement Machine Servicers and Repairers","34260"},
            {"Medical Secretaries","34330"},
            {"Outdoor Power Equipment and Other Small Engine Mechanics","34520"},
            {"Machine Tool Cutting Setters, Operators, and Tenders, Metal and Plastic","34530"},
            {"Customer Service Representatives","34560"},
            {"Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic","34560"},
            {"Pesticide Handlers, Sprayers, and Applicators, Vegetation","34570"},
            {"Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic","34580"},
            {"Health Practitioner Support Technologists and Technicians","34710"},
            {"Office and Administrative Support Workers, All Other","34730"},
            {"Fence Erectors","34840"},
            {"Rock Splitters, Quarry","34870"},
            {"Supervisors of Food Preparation and Serving Workers","34930"},
            {"Medical Equipment Preparers","34950"},
            {"Conveyor Operators and Tenders","35100"},
            {"Electromechanical Equipment Assemblers","35140"},
            {"Religious Workers, All Other","35160"},
            {"Secretaries and Administrative Assistants, Except Legal, Medical, and Executive","35200"},
            {"Automotive Glass Installer","35210"},
            {"Skincare Specialists","35300"},
            {"Animal Control Worker","35330"},
            {"Crushing, Grinding, Polishing, Mixing, and Blending Workers","35370"},
            {"Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic","35380"},
            {"Pourers and Casters, Metal","35390"},
            {"Emergency Medical Technicians and Paramedics","35430"},
            {"Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders","35560"},
            {"Craft Artists","35710"},
            {"Medical Transcriptionists","35720"},
            {"New Accounts Clerks","35820"},
            {"Metal Workers and Plastic Workers, All Other","35910"},
            {"Tree Trimmers and Pruners","36030"},
            {"Logging Workers, All Other","36210"},
            {"Motorcycle Mechanics","36240"},
            {"Psychiatric Technicians","36280"},
            {"Billing and Posting Clerk","36300"},
            {"Correspondence Clerks","36340"},
            {"Refuse and Recyclable Material Collectors","36370"},
            {"Mixing and Blending Machine Setters, Operators, and Tenders","36410"},
            {"Small Engine Mechanics","36420"},
            {"Printing Workers","36440"},
            {"Motor Vehicle Operators","36460"},
            {"Forest, Conservation, and Logging Workers","36470"},
            {"Construction Laborers","36550"},
            {"Bill and Account Collector","36600"},
            {"Paperhangers","36610"},
            {"Forming Machine Setters, Operators, and Tenders, Metal and Plastic","36650"},
            {"Financial Clerks","36680"},
            {"Ophthalmic Medical Technicians","36690"},
            {"Reservation and Transportation Ticket Agents and Travel Clerks","36780"},
            {"Opticians, Dispensing","36820"},
            {"Forging Machine Setters, Operators, and Tenders, Metal and Plastic","36910"},
            {"Dental Assistants","36920"},
            {"Healthcare Support Workers, All Other","36920"},
            {"Travel Guides","36920"},
            {"Logging Equipment Operators","36930"},
            {"Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders","36970"},
            {"Printing Press Operators","37020"},
            {"Material Moving Workers, All Other","37060"},
            {"Helpers--Extraction Workers","37080"},
            {"Painting Workers","37110"},
            {"Watch Repairers","37110"},
            {"Paper Goods Machine Setters, Operators, and Tenders","37160"},
            {"Models","37240"},
            {"Recreational Vehicle Service Technicians","37380"},
            {"Other Teachers and Instructors","37420"},
            {"Log Graders and Scalers","37420"},
            {"Funeral Service Workers","37460"},
            {"Slot Supervisors","37550"},
            {"Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders","37590"},
            {"Tool Grinders, Filers, and Sharpeners","37590"},
            {"Semiconductor Processors","37600"},
            {"Medical, Dental, and Ophthalmic Laboratory Technicians","37610"},
            {"Logging Workers","37640"},
            {"Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic","37660"},
            {"Cooks, Private Household","37680"},
            {"Proofreaders and Copy Markers","37690"},
            {"Septic Tank Servicers and Sewer Pipe Cleaners","37880"},
            {"Musicians, Singers, and Related Workers","37889"},
            {"Credit Authorizers, Checkers, and Clerks","37920"},
            {"Driver/Sales Workers and Truck Drivers","38030"},
            {"Rehabilitation Counselors","38040"},
            {"Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic","38080"},
            {"Floor Sanders and Finishers","38160"},
            {"Highway Maintenance Workers","38200"},
            {"Court, Municipal, and License Clerks","38230"},
            {"Forest and Conservation Technicians","38260"},
            {"Parking Enforcement Workers","38280"},
            {"Model Makers, Wood","38330"},
            {"Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic","38420"},
            {"Farm Equipment Mechanics and Service Technicians","38510"},
            {"Transportation Workers, All Other","38520"},
            {"Musical Instrument Repairers and Tuners","38590"},
            {"First-Line Supervisors of Personal Service Workers","38670"},
            {"Roustabouts, Oil and Gas","38700"},
            {"Word Processors and Typists","38710"},
            {"Computer-Controlled Machine Tool Operators, Metal and Plastic","38720"},
            {"Travel Agents","38750"},
            {"Information and Record Clerks, All Other","38770"},
            {"Insulation Workers, Floor, Ceiling, and Wall","38810"},
            {"Home Appliance Repairers","38820"},
            {"Metal Workers and Plastic Workers","38850"},
            {"Maintenance and Repair Workers, General","38950"},
            {"Auditing Clerk","38990"},
            {"Computer, Automated Teller, and Office Machine Repairers","38990"},
            {"Agricultural and Food Science Technician","39000"},
            {"Medical Appliance Technicians","39020"},
            {"Structural Metal Fabricators and Fitters","39040"},
            {"Preschool and Kindergarten Teachers","39090"},
            {"Human Resources Assistants, Except Payroll and Timekeeping","39180"},
            {"Loan Interviewers and Clerks","39210"},
            {"Secretaries and Administrative Assistants","39360"},
            {"Inspectors, Testers, Sorters, Samplers, and Weighers","39410"},
            {"Construction and Related Workers, All Other","39500"},
            {"Motorboat Mechanics and Service Technicians","39500"},
            {"Insurance Claims and Policy Processing Clerks","39560"},
            {"Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic","39620"},
            {"Electronic Home Entertainment Equipment Installers and Repairers","39670"},
            {"Model Makers and Patternmakers, Wood","39840"},
            {"Supervisors of Personal Care and Service Workers","39870"},
            {"Mechanical Door Repairers","39900"},
            {"Police, Fire, and Ambulance Dispatchers","40000"},
            {"Coaches and Scouts","40050"},
            {"Transportation Security Screeners","40050"},
            {"First-Line Supervisors of Housekeeping and Janitorial Workers","40060"},
            {"Prepress Technicians and Workers","40060"},
            {"Solar Photovoltaic Installers","40070"},
            {"Dispatchers","40140"},
            {"Community Health Workers","40150"},
            {"Bus Drivers, Transit and Intercity","40160"},
            {"Dispatchers, Except Police, Fire, and Ambulance","40210"},
            {"Tire Builders","40230"},
            {"Photographers","40280"},
            {"Metal Furnace Operators, Tenders, Pourers, and Casters","40390"},
            {"Medical Records and Health Information Technicians","40430"},
            {"Public Address System and Other Announcers","40440"},
            {"Painters and Paperhangers","40490"},
            {"Dental Laboratory Technicians","40520"},
            {"Painters, Construction and Maintenance","40540"},
            {"Sales and Related Workers, All Other","40540"},
            {"Welding, Soldering, and Brazing Workers","40560"},
            {"Roofers","40630"},
            {"Computer Control Programmers and Operators","40650"},
            {"Automotive Service Technician","40720"},
            {"Telephone Operators","40820"},
            {"Meter Readers, Utilities","40900"},
            {"Welders, Cutters, Solderers, and Brazers","40970"},
            {"Fitness Trainers and Aerobics Instructors","40970"},
            {"Procurement Clerks","41010"},
            {"Tank Car, Truck, and Ship Loaders","41010"},
            {"Installation, Maintenance, and Repair Workers, All Other","41120"},
            {"Rolling Machine Setters, Operators, and Tenders, Metal and Plastic","41200"},
            {"Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders","41210"},
            {"Locksmiths and Safe Repairers","41270"},
            {"Automotive Technician","41290"},
            {"Motorboat Operators","41350"},
            {"Medical and Clinical Laboratory Technicians","41420"},
            {"Coach","41470"},
            {"Embalmers","41490"},
            {"Patternmakers, Metal and Plastic","41500"},
            {"Timing Device Assemblers and Adjusters","41510"},
            {"Patternmakers, Wood","41550"},
            {"Engine and Other Machine Assemblers","41750"},
            {"Fallers","41750"},
            {"Pipelayers","41910"},
            {"Communications Equipment Operators, All Other","41990"},
            {"Plasterers and Stucco Masons","42070"},
            {"Cement Masons and Concrete Finishers","42080"},
            {"Machinists","42120"},
            {"Payroll and Timekeeping Clerks","42130"},
            {"Computer Operators","42140"},
            {"Cement Masons, Concrete Finishers, and Terrazzo Workers","42150"},
            {"Financial Clerks, All Other","42270"},
            {"Self-Enrichment Education Teachers","42350"},
            {"Jewelers and Precious Stone and Metal Workers","42380"},
            {"Dancers and Choreographers","42410"},
            {"Heavy and Tractor-Trailer Truck Drivers","42500"},
            {"Camera and Photographic Equipment Repairers","42510"},
            {"Floor Layers, Except Carpet, Wood, and Hard Tiles","42520"},
            {"Legislators","42530"},
            {"First-Line Supervisors of Building and Grounds Cleaning and Maintenance Workers","42680"},
            {"Metal-Refining Furnace Operators and Tenders","42790"},
            {"First-Line Supervisors of Retail Sales Workers","42900"},
            {"Sailors and Marine Oilers","42910"},
            {"Substance Abuse and Behavioral Disorder Counselors","42920"},
            {"Stonemasons","42970"},
            {"Vehicle and Mobile Equipment Mechanics, Installers, and Repairers","42990"},
            {"Paving, Surfacing, and Tamping Equipment Operators","43020"},
            {"Eligibility Interviewers, Government Programs","43040"},
            {"Massage Therapists","43170"},
            {"Carpet, Floor, and Tile Installers and Finishers","43180"},
            {"Carpet Installers","43210"},
            {"Electric Motor, Power Tool, and Related Repairers","43760"},
            {"Agricultural Inspector","43810"},
            {"Desktop Publishers","43900"},
            {"Farm Labor Contractors","43920"},
            {"Tile and Marble Setters","44010"},
            {"Licensed Practical and Licensed Vocational Nurses","44030"},
            {"Dredge Operators","44040"},
            {"Broadcast Technician","44050"},
            {"Hazardous Materials Removal Workers","44150"},
            {"Statistical Assistants","44220"},
            {"Community and Social Service Specialists, All Other","44370"},
            {"Education, Training, and Library Workers, All Other","44380"},
            {"Cargo and Freight Agents","44470"},
            {"Excavating and Loading Machine and Dragline Operators","44520"},
            {"Maintenance Workers, Machinery","44540"},
            {"Automotive Body Repairer","44590"},
            {"Physical Therapist Assistants and Aides","44590"},
            {"Animal Breeder","44650"},
            {"Tax Preparers","44730"},
            {"Insulation Workers","44740"},
            {"Forest Fire Inspectors and Prevention Specialists","44740"},
            {"Surveying and Mapping Technicians","44800"},
            {"Dredge, Excavating, and Loading Machine Operators","44810"},
            {"Security and Fire Alarm Systems Installers","44860"},
            {"Museum Technicians and Conservators","44880"},
            {"Bailiff","44900"},
            {"Painters, Transportation Equipment","44920"},
            {"Mental Health Counselors","45080"},
            {"Directors, Religious Activities and Education","45160"},
            {"Announcers","45170"},
            {"Biological Technician","45230"},
            {"Correctional Officer","45310"},
            {"Correctional Officers and Jailers","45320"},
            {"Glaziers","45420"},
            {"Drywall and Ceiling Tile Installers","45510"},
            {"Model Makers and Patternmakers, Metal and Plastic","45620"},
            {"Health Technologists and Technicians, All Other","45730"},
            {"Social Science Research Assistants","45760"},
            {"Health Technologists and Technicians","45850"},
            {"Chefs and Head Cooks","45920"},
            {"Surgical Technologists","45940"},
            {"Bridge and Lock Tender","45980"},
            {"Religious Workers","46020"},
            {"Terrazzo Workers and Finishers","46050"},
            {"Bus and Truck Mechanics and Diesel Engine Specialists","46110"},
            {"Chemical Processing Machine Setters, Operators, and Tenders","46150"},
            {"Counselors, Social Workers, and Other Community and Social Service Specialists","46170"},
            {"Pump Operators, Except Wellhead Pumpers","46200"},
            {"Construction Trades Workers","46290"},
            {"Other Construction and Related Workers","46370"},
            {"Radio and Television Announcers","46410"},
            {"Layout Workers, Metal and Plastic","46430"},
            {"Legal Secretaries","46470"},
            {"Environmental Science and Protection Technicians, Including Health","46540"},
            {"Reporters and Correspondents","46560"},
            {"Child, Family, and School Social Workers","46610"},
            {"Audio and Video Equipment Technician","46630"},
            {"Flight Attendants","46750"},
            {"Drywall Installers, Ceiling Tile Installers, and Tapers","46760"},
            {"Carpenters","46780"},
            {"Water and Wastewater Treatment Plant and System Operators","46790"},
            {"First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers","46900"},
            {"First-Line Supervisors of Gaming Workers","46940"},
            {"Athletic Trainer","46940"},
            {"Extraction Workers","46970"},
            {"Mental Health and Substance Abuse Social Workers","47190"},
            {"Radio Operators","47200"},
            {"Designers","47370"},
            {"Heating, Air Conditioning, and Refrigeration Mechanics and Installers","47380"},
            {"Teachers and Instructors, All Other, Except Substitute Teachers","47410"},
            {"Rail Yard Engineers, Dinkey Operators, and Hostlers","47600"},
            {"Life, Physical, and Social Science Technicians","47640"},
            {"Traffic Technicians","47660"},
            {"Riggers","47770"},
            {"Other Sales and Related Workers","47780"},
            {"Recreational Therapists","47790"},
            {"Counselors, All Other","47950"},
            {"Broadcast and Sound Engineering Technician","48140"},
            {"Clergy","48150"},
            {"Heavy Vehicle and Mobile Equipment Service Technicians and Mechanics","48180"},
            {"Wellhead Pumpers","48180"},
            {"Production, Planning, and Expediting Clerks","48210"},
            {"Model Makers, Metal and Plastic","48210"},
            {"Audio-Visual and Multimedia Collections Specialist","48220"},
            {"Precision Instrument and Equipment Repairers","48230"},
            {"First-Line Supervisors of Farming, Fishing, and Forestry Workers","48290"},
            {"Life, Physical, and Social Science Technicians, All Other","48360"},
            {"Interpreters and Translators","48360"},
            {"Construction Equipment Operators","48380"},
            {"Pumping Station Operators","48570"},
            {"Chemical Technicians","48730"},
            {"Counselors","48790"},
            {"Aircraft Cargo Handling Supervisor","48870"},
            {"Refractory Materials Repairers, Except Brickmasons","48920"},
            {"Librarians, Curators, and Archivists","48960"},
            {"Fabric and Apparel Patternmakers","49040"},
            {"Postal Service Clerks","49090"},
            {"Operating Engineers and Other Construction Equipment Operators","49110"},
            {"Extraction Workers, All Other","49140"},
            {"Mining Machine Operators, All Other","49270"},
            {"Credit Counselors","49310"},
            {"Firefighters","49330"},
            {"Medical Equipment Repairers","49400"},
            {"First-Line Supervisors of Protective Service Workers, All Other","49540"},
            {"Chemical Equipment Operators and Tenders","49640"},
            {"Social Workers","49670"},
            {"First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand","49670"},
            {"Fire Fighting and Prevention Workers","49690"},
            {"Respiratory Therapy Technicians","49720"},
            {"Exercise Physiologists","49740"},
            {"Loading Machine Operators, Underground Mining","49740"},
            {"Sheet Metal Workers","49810"},
            {"Title Examiners, Abstractors, and Searchers","49840"},
            {"Insulation Workers, Mechanical","49970"},
            {"Mobile Heavy Equipment Mechanics, Except Engines","50080"},
            {"First-Line Supervisors of Sales Workers","50120"},
            {"Gaming Supervisors","50130"},
            {"Service Unit Operators, Oil, Gas, and Mining","50150"},
            {"Industrial Machinery Installation, Repair, and Maintenance Workers","50160"},
            {"Stonemasons","50200"},
            {"Electrical and Electronic Equipment Mechanics, Installers, and Repairers","50380"},
            {"Tax Examiners, Collectors and Preparers, and Revenue Agents","50410"},
            {"Mining Machine Operators","50530"},
            {"Postal Service Mail Sorters, Processors, and Processing Machine Operators","50650"},
            {"Continuous Mining Machine Operators","50660"},
            {"Hoist and Winch Operators","50680"},
            {"Postal Service Workers","50700"},
            {"Derrick Operators, Oil and Gas","50710"},
            {"Mine Cutting and Channeling Machine Operators","50720"},
            {"Actor","50943"},
            {"News Analysts, Reporters and Correspondents","50970"},
            {"Aircraft Assembler","51040"},
            {"Control and Valve Installers and Repairers","51060"},
            {"Postal Service Mail Carriers","51130"},
            {"Tool and Die Makers","51130"},
            {"Environmental Engineering Technicians","51170"},
            {"Meeting, Convention, and Event Planners","51200"},
            {"Civil Engineering Technicians","51330"},
            {"Rail-Track Laying and Maintenance Equipment Operators","51340"},
            {"Industrial Machinery Mechanics","51470"},
            {"Choreographers","51560"},
            {"Computer Numerically Controlled Machine Tool Programmers, Metal and Plastic","51630"},
            {"Graphic Designers","51640"},
            {"Brokerage Clerk","51640"},
            {"Brickmason","51750"},
            {"Curator","51750"},
            {"Clinical Laboratory Technologists and Technicians","51810"},
            {"Farm and Home Management Advisors","51820"},
            {"Earth Drillers, Except Oil and Gas","51840"},
            {"Media and Communication Workers, All Other","52200"},
            {"Art and Design Worker","52240"},
            {"Paralegals and Legal Assistants","52390"},
            {"Computer User Support Specialists","52430"},
            {"Explosives Workers, Ordnance Handling Experts, and Blasters","52580"},
            {"Millwrights","52650"},
            {"Derrick, Rotary Drill, and Service Unit Operators, Oil, Gas, and Mining","52680"},
            {"Education Administrators, Preschool and Childcare Center/Program","52760"},
            {"Private Detectives and Investigators","52840"},
            {"Hearing Aid Specialists","52850"},
            {"Costume Attendants","52870"},
            {"Radio, Cellular, and Tower Equipment Installers and Repairers","52940"},
            {"Morticians, Undertakers, and Funeral Directors","52990"},
            {"Wind Turbine Service Technicians","53030"},
            {"Tapers","53080"},
            {"Media and Communication Equipment Workers","53220"},
            {"Architectural and Civil Drafter","53470"},
            {"Marriage and Family Therapists","53520"},
            {"Legal Support Workers","53550"},
            {"Mathematical Technicians","53630"},
            {"Food Service Managers","53640"},
            {"Drafters, All Other","53660"},
            {"Pipelayers, Plumbers, Pipefitters, and Steamfitters","53860"},
            {"Archivist","53880"},
            {"Railroad Brake, Signal, and Switch Operators","53990"},
            {"Healthcare Social Workers","54020"},
            {"Reinforcing Iron and Rebar Workers","54030"},
            {"Secondary Education Teacher","54060"},
            {"Probation Officers and Correctional Treatment Specialists","54080"},
            {"Precision Instrument and Equipment Repairers, All Other","54110"},
            {"Rail Car Repairers","54130"},
            {"Fine Artists, Including Painters, Sculptors, and Illustrators","54170"},
            {"Telecommunications Line Installers and Repairers","54200"},
            {"Vocational Education Teachers, Postsecondary","54260"},
            {"Supervisors of Transportation and Material Moving Workers","54290"},
            {"Radio and Telecommunications Equipment Installers and Repairers","54420"},
            {"Telecommunications Equipment Installers and Repairers, Except Line Installers","54510"},
            {"Kindergarten Teachers, Except Special Education","54510"},
            {"Locomotive Firers","54540"},
            {"Crane and Tower Operators","54560"},
            {"Commercial Divers","54640"},
            {"Court Reporters","54720"},
            {"Structural Iron and Steel Workers","54750"},
            {"Set and Exhibit Designers","54920"},
            {"Fish and Game Wardens","54970"},
            {"Plumbers, Pipefitters, and Steamfitters","55100"},
            {"Mine Shuttle Car Operators","55120"},
            {"Pile-Driver Operators","55150"},
            {"Physical Therapist Assistants","55250"},
            {"Airfield Operations Specialist","55400"},
            {"Executive Secretaries and Executive Administrative Assistants","55460"},
            {"Roof Bolters, Mining","55500"},
            {"Interior Designers","55510"},
            {"Plant and System Operators, All Other","55530"},
            {"Electricians","55590"},
            {"Control and Valve Installers and Repairers, Except Mechanical Door","55760"},
            {"Drafters","55820"},
            {"Computer Support Specialists","55980"},
            {"Cardiovascular Technologists and Technicians","56100"},
            {"First-Line Supervisors of Office and Administrative Support Workers","56170"},
            {"Industrial Engineering Technicians","56320"},
            {"Electro-Mechanical Technicians","56320"},
            {"Preschool, Primary, Secondary, and Special Education School Teachers","56370"},
            {"Mechanical Engineering Technicians","56390"},
            {"Healthcare Practitioners and Technical Workers, All Other","56400"},
            {"Educational, Guidance, School, and Vocational Counselors","56490"},
            {"Mechanical Drafters","56610"},
            {"Drafters, Engineering Technicians, and Mapping Technicians","56650"},
            {"Electrical and Electronics Repairers, Commercial and Industrial Equipment","56670"},
            {"Health Educators","56690"},
            {"Railroad Conductors and Yardmasters","56760"},
            {"Law Enforcement Workers","56860"},
            {"Curators","56990"},
            {"Fundraisers","57170"},
            {"Rail Transportation Workers","57230"},
            {"Tax Examiners and Collectors, and Revenue Agents","57280"},
            {"Gas Compressor and Gas Pumping Station Operators","57510"},
            {"Special Education Teachers, All Other","57670"},
            {"Elementary School Teachers, Except Special Education","57730"},
            {"Lodging Managers","57810"},
            {"Social Workers, All Other","57970"},
            {"Locomotive Engineers and Operators","57980"},
            {"Fire Inspectors","58020"},
            {"Elementary and Middle School Teachers","58060"},
            {"Career/Technical Education Teachers, Secondary School","58170"},
            {"Special Education Teachers, Preschool","58210"},
            {"Entertainers and Performers, Sports and Related Workers","58380"},
            {"Appraiser","58400"},
            {"Real Estate Sales Agents","58410"},
            {"Dietitians and Nutritionists","58410"},
            {"First-Line Supervisors of Transportation and Material-Moving Machine and Vehicle Operators","58470"},
            {"Career/Technical Education Teachers, Middle School","58480"},
            {"Engineering Technicians, Except Drafters","58490"},
            {"Radiologic Technologists","58520"},
            {"Special Education Teachers, Kindergarten and Elementary School","58640"},
            {"Middle School Teachers, Except Special and Career/Technical Education","58760"},
            {"Rail Transportation Workers, All Other","58760"},
            {"Plant and System Operators","58780"},
            {"Librarians","58930"},
            {"Music Directors and Composers","59040"},
            {"Chemical Plant and System Operators","59070"},
            {"Electrical and Electronics Installers and Repairers, Transportation Equipment","59080"},
            {"Therapists, All Other","59210"},
            {"Wholesale and Retail Buyers, Except Farm Products","59270"},
            {"Survey Researchers","59340"},
            {"Locomotive Engineers","59360"},
            {"Camera Operators, Television, Video, and Motion Picture","59360"},
            {"Respiratory Therapists","59640"},
            {"Special Education Teachers","59800"},
            {"Fire Inspectors and Investigators","59800"},
            {"Judicial Law Clerks","59910"},
            {"First-Line Supervisors of Production and Operating Workers","59930"},
            {"Construction and Building Inspectors","60030"},
            {"Forensic Science Technicians","60090"},
            {"Line Installers and Repairers","60160"},
            {"Aircraft Mechanic","60160"},
            {"Avionics Technician","60200"},
            {"Secondary School Teachers","60270"},
            {"Special Education Teachers, Middle School","60300"},
            {"Rotary Drill Operators, Oil and Gas","60380"},
            {"Secondary School Teachers, Except Special and Career/Technical Education","60440"},
            {"Stationary Engineers and Boiler Operators","60480"},
            {"Subway and Streetcar Operators","60580"},
            {"Foresters","60650"},
            {"Boilermaker","60660"},
            {"Geological and Petroleum Technicians","60710"},
            {"Labor Relations Specialists","60930"},
            {"Historians","61120"},
            {"Police Officers","61270"},
            {"Police and Sheriff's Patrol Officers","61270"},
            {"Advertising Sales Agent","61690"},
            {"Medical and Clinical Laboratory Technologists","61860"},
            {"Electrical and Electronics Engineering Technicians","61870"},
            {"Surveyors","61880"},
            {"Media and Communication Workers","61910"},
            {"Diagnostic Related Technologists and Technicians","62080"},
            {"Transit and Railroad Police","62090"},
            {"Special Education Teachers, Secondary School","62180"},
            {"Designers, All Other","62220"},
            {"Buyers and Purchasing Agents, Farm Products","62280"},
            {"Sales Representatives, Services, All Other","62360"},
            {"Training and Development Specialists","62460"},
            {"Surveyors, Cartographers, and Photogrammetrists","62650"},
            {"Signal and Track Switch Repairers","62650"},
            {"First-Line Supervisors of Correctional Officers","62770"},
            {"Engineering Technicians, Except Drafters, All Other","62820"},
            {"Real Estate Brokers and Sales Agents","62850"},
            {"Conservation Scientists and Foresters","62860"},
            {"Electrical and Electronics Drafters","62890"},
            {"Human Resources Workers","63280"},
            {"Sound Engineering Technicians","63340"},
            {"Human Resources Specialists","63710"},
            {"Conservation Scientists","63800"},
            {"Buyers and Purchasing Agents","64170"},
            {"Zoologists and Wildlife Biologists","64230"},
            {"Anthropologist","64290"},
            {"Claims Adjusters, Examiners, and Investigators","64300"},
            {"Claims Adjusters, Appraisers, Examiners, and Investigators","64350"},
            {"Criminal Justice and Law Enforcement Teachers, Postsecondary","64460"},
            {"Legal Support Workers, All Other","64530"},
            {"Water Transportation Workers","64720"},
            {"Insurance Sales Agents","64790"},
            {"Cost Estimators","64810"},
            {"Instructional Coordinators","64870"},
            {"Editors","64910"},
            {"Compensation, Benefits, and Job Analysis Specialists","65100"},
            {"Insurance Appraisers, Auto Damage","65300"},
            {"Cartographers and Photogrammetrists","65410"},
            {"Electrical Power-Line Installers and Repairers","65650"},
            {"Public Relations Specialists","65830"},
            {"Gas Plant Operators","65830"},
            {"First-Line Supervisors of Mechanics, Installers, and Repairers","65890"},
            {"Soil and Plant Scientists","65980"},
            {"Petroleum Pump System Operators, Refinery Operators, and Gaugers","66020"},
            {"Recreation and Fitness Studies Teachers, Postsecondary","66090"},
            {"Purchasing Agents, Except Wholesale, Retail, and Farm Products","66120"},
            {"Makeup Artists, Theatrical and Performance","66560"},
            {"Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products","66790"},
            {"First-Line Supervisors of Construction Trades and Extraction Workers","66820"},
            {"Computer Network Support Specialists","67260"},
            {"Writers and Editors","68090"},
            {"Education Teachers, Postsecondary","68200"},
            {"Property, Real Estate, and Community Association Managers","68240"},
            {"Magnetic Resonance Imaging Technologists","68340"},
            {"Education and Library Science Teachers, Postsecondary","68560"},
            {"Landscape Architects","68600"},
            {"Aerospace Engineering Technician","68620"},
            {"Social Work Teachers, Postsecondary","69030"},
            {"Arbitrator","69060"},
            {"Home Economics Teachers, Postsecondary","69090"},
            {"Sales Representatives, Services","69100"},
            {"Writers and Authors","69130"},
            {"Compliance Officers","69180"},
            {"Agricultural and Food Scientist","69230"},
            {"Social and Community Service Managers","69430"},
            {"Foreign Language and Literature Teachers, Postsecondary","69520"},
            {"Commercial and Industrial Designers","69820"},
            {"Farmers, Ranchers, and Other Agricultural Managers","69880"},
            {"Orthotists and Prosthetists","69960"},
            {"Market Research Analysts and Marketing Specialists","70030"},
            {"Communications Teachers, Postsecondary","70290"},
            {"Multimedia Artists and Animators","70300"},
            {"Supervisors of Protective Service Workers","70530"},
            {"Postmasters and Mail Superintendents","70540"},
            {"Web Developers","70660"},
            {"Urban and Regional Planners","70680"},
            {"Diagnostic Medical Sonographers","70880"},
            {"Business Operations Specialists","70900"},
            {"Media and Communication Equipment Workers, All Other","70920"},
            {"Registered Nurses","71000"},
            {"Postsecondary Teachers, All Other","71060"},
            {"Power Plant Operators","71070"},
            {"Sales Representatives, Wholesale and Manufacturing","71080"},
            {"English Language and Literature Teachers, Postsecondary","71210"},
            {"Television, Video, and Motion Picture Camera Operators and Editors","71500"},
            {"Animal Scientist","71830"},
            {"Food Scientists and Technologists","72030"},
            {"Transportation Inspectors","72220"},
            {"Electrical and Electronics Repairers, Powerhouse, Substation, and Relay","72450"},
            {"Financial Specialists, All Other","72480"},
            {"Insurance Underwriters","72650"},
            {"Dental Hygienists","72720"},
            {"Credit Counselors and Loan Officers","72810"},
            {"Library Science Teachers, Postsecondary","73030"},
            {"Nursing Instructors and Teachers, Postsecondary","73150"},
            {"Fashion Designers","73180"},
            {"Technical Writers","73350"},
            {"Business Operations Specialists, All Other","73480"},
            {"Art Teacher","73660"},
            {"Emergency Management Directors","73750"},
            {"Environmental Scientists and Specialists, Including Health","73930"},
            {"Genetic Counselors","74570"},
            {"Geographers","74920"},
            {"First-Line Supervisors of Fire Fighting and Prevention Workers","74970"},
            {"Nuclear Medicine Technologists","74990"},
            {"Philosophy and Religion Teachers, Postsecondary","75140"},
            {"Budget Analysts","75150"},
            {"Loan Officers","75170"},
            {"Power Plant Operators, Distributors, and Dispatchers","75190"},
            {"Accountant","75280"},
            {"Clinical, Counseling, and School Psychologists","76040"},
            {"Therapists","76220"},
            {"Microbiologists","76230"},
            {"History Teachers, Postsecondary","76670"},
            {"Art Teacher","76710"},
            {"Sociology Teachers, Postsecondary","76750"},
            {"Speech-Language Pathologists","76900"},
            {"Epidemiologists","76900"},
            {"Mathematical Science Teachers, Postsecondary","77290"},
            {"Elevator Installers and Repairers","77350"},
            {"Audiologist","77420"},
            {"Logisticians","77470"},
            {"Postsecondary Teachers","77480"},
            {"Artist","77580"},
            {"Gaming Managers","77770"},
            {"Chemists","77860"},
            {"Psychologists","77950"},
            {"Chiropractors","78370"},
            {"Agricultural Engineer","78490"},
            {"Social Scientists and Related Workers","78520"},
            {"Financial Specialists","78730"},
            {"Nuclear Technicians","78850"},
            {"First-Line Supervisors of Law Enforcement Workers","78950"},
            {"Ship Engineers","78970"},
            {"Ship and Boat Captains and Operators","79000"},
            {"Chemists and Materials Scientists","79130"},
            {"Psychology Teachers, Postsecondary","79370"},
            {"Biological Scientist","79610"},
            {"Detectives and Criminal Investigators","79620"},
            {"Geography Teachers, Postsecondary","79690"},
            {"Credit Analysts","79720"},
            {"Social Sciences Teachers, Postsecondary, All Other","79820"},
            {"Life Scientists, All Other","79870"},
            {"Math and Computer Teachers, Postsecondary","80140"},
            {"Real Estate Brokers","80210"},
            {"Film and Video Editors","80300"},
            {"Power Distributors and Dispatchers","80400"},
            {"Athlete","80490"},
            {"Social Scientists and Related Workers, All Other","80650"},
            {"Area, Ethnic, and Cultural Studies Teacher","81700"},
            {"Life Scientists","81920"},
            {"Sociologists","82100"},
            {"Network and Computer Systems Administrators","82200"},
            {"Environmental Scientists and Geoscientists","82480"},
            {"Architect","82850"},
            {"Education Administrators, All Other","82970"},
            {"Captains, Mates, and Pilots of Water Vessels","83150"},
            {"Hydrologists","83440"},
            {"Social Sciences Teachers, Postsecondary","84180"},
            {"Operations Research Analysts","84180"},
            {"Database Administrators","84250"},
            {"Computer Programmers","84360"},
            {"Statisticians","84440"},
            {"Radiation Therapists","84460"},
            {"Funeral Service Managers","84470"},
            {"Commercial Pilots","84510"},
            {"Computer Science Teachers, Postsecondary","84700"},
            {"Architecture Teacher","84880"},
            {"First-Line Supervisors of Non-Retail Sales Workers","84910"},
            {"Health Diagnosing and Treating Practitioners, All Other","85120"},
            {"Physical Scientists","85180"},
            {"Anthropology Teacher","85440"},
            {"Physical Therapists","85790"},
            {"First-Line Supervisors of Police and Detectives","85810"},
            {"Producer","85850"},
            {"Chemistry Teachers, Postsecondary","86070"},
            {"Biological Science Teacher","86830"},
            {"Industrial Engineers","86990"},
            {"Industrial Engineers, Including Health and Safety","87070"},
            {"Air Transportation Worker","87140"},
            {"Database and Systems Administrators and Network Architects","87400"},
            {"Health and Safety Engineers, Except Mining Safety Engineers and Inspectors","87810"},
            {"Civil Engineers","87940"},
            {"Environmental Engineers","88040"},
            {"Mechanical Engineers","88190"},
            {"Life Sciences Teachers, Postsecondary","88240"},
            {"Financial Examiners","88310"},
            {"Environmental Science Teachers, Postsecondary","88570"},
            {"Political Science Teachers, Postsecondary","88680"},
            {"Nuclear Power Reactor Operators","88820"},
            {"Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products","89170"},
            {"Broadcast News Analyst","89240"},
            {"Law, Criminal Justice, and Social Work Teachers, Postsecondary","89470"},
            {"Producers and Directors","89670"},
            {"Physical Sciences Teachers, Postsecondary","89840"},
            {"Computer Systems Analysts","90180"},
            {"Atmospheric and Space Scientist","90210"},
            {"Computer and Information Analysts","90600"},
            {"Education Administrators","90970"},
            {"Forestry and Conservation Science Teachers, Postsecondary","91030"},
            {"Biomedical Engineer","91230"},
            {"Management Analysts","91770"},
            {"Business Teachers, Postsecondary","92220"},
            {"Industrial-Organizational Psychologists","92320"},
            {"Space Sciences Teacher","92540"},
            {"Medical Scientists","92900"},
            {"Education Administrators, Elementary and Secondary School","92940"},
            {"Psychologists, All Other","93050"},
            {"Administrative Law Judges, Adjudicators, and Hearing Officers","93140"},
            {"Information Security Analysts","93250"},
            {"Biochemist","93390"},
            {"Nurse Midwives","93610"},
            {"Medical Scientists, Except Epidemiologists","93730"},
            {"Physics Teachers, Postsecondary","93950"},
            {"Materials Engineers","94690"},
            {"Administrative Services Manager","94840"},
            {"Materials Scientists","94940"},
            {"Transportation, Storage, and Distribution Managers","95130"},
            {"Engineers","95240"},
            {"Agricultural Sciences Teacher","95280"},
            {"Financial Analysts","95320"},
            {"Agent","95810"},
            {"Health Diagnosing and Treating Practitioners","97030"},
            {"Electrical Engineers","97340"},
            {"Construction Managers","97510"},
            {"Software Developers and Programmers","97930"},
            {"Engineers, All Other","98150"},
            {"Physical Scientists, All Other","98240"},
            {"Veterinarians","99000"},
            {"Physician Assistants","99270"},
            {"Electrical and Electronics Engineers","99520"},
            {"Financial Analysts and Advisors","99730"},
            {"Marine Engineers and Naval Architects","100090"},
            {"Engineering and Architecture Teachers, Postsecondary","101040"},
            {"Nurse Practitioners","101260"},
            {"Art Director","101990"},
            {"Software Developers, Applications","102160"},
            {"Electronics Engineers, Except Computer","102390"},
            {"Air Traffic Controller Specialist","102580"},
            {"Education Administrators, Postsecondary","102610"},
            {"Securities, Commodities, and Financial Services Sales Agents","102860"},
            {"Computer Network Architects","103100"},
            {"Political Scientists","103210"},
            {"Judges, Magistrates, and Other Judicial Workers","103390"},
            {"Industrial Production Managers","103720"},
            {"Chemical Engineers","103960"},
            {"Engineering Teachers, Postsecondary","104220"},
            {"Health Teachers, Postsecondary","104470"},
            {"Geoscientists, Except Hydrologists and Geographers","105720"},
            {"Nuclear Engineers","106060"},
            {"Medical and Health Services Managers","106070"},
            {"Economics Teachers, Postsecondary","106980"},
            {"Sales Engineers","107160"},
            {"Mining and Geological Engineers, Including Mining Safety Engineers","107880"},
            {"Software Developers, Systems Software","108760"},
            {"Economists","109230"},
            {"Astronomers","110220"},
            {"Actuary","110560"},
            {"Aerospace Engineer","110570"},
            {"Managers, All Other","111230"},
            {"Training and Development Managers","111680"},
            {"Mathematicians","112560"},
            {"Advertising Manager","113610"},
            {"Purchasing Managers","114130"},
            {"Health Specialties Teachers, Postsecondary","114510"},
            {"Computer Hardware Engineers","114970"},
            {"Computer and Information Research Scientists","115580"},
            {"Optometrists","115750"},
            {"Judges, Magistrate Judges, and Magistrates","116100"},
            {"Human Resources Managers","117080"},
            {"Physicist","117660"},
            {"Personal Financial Advisors","118050"},
            {"Physicists","118500"},
            {"Air Traffic Controller","118740"},
            {"Pharmacists","119270"},
            {"Flight Engineer","119360"},
            {"Public Relations and Fundraising Managers","119390"},
            {"General and Operations Managers","119460"},
            {"Operations Specialties Managers","120900"},
            {"Compensation and Benefits Managers","121630"},
            {"Top Executives","124210"},
            {"Law Teachers, Postsecondary","126230"},
            {"Sales Managers","130400"},
            {"Sales Manager","131670"},
            {"Lawyers, Judges, and Related Workers","132380"},
            {"Marketing and Sales Managers","133950"},
            {"Financial Managers","134330"},
            {"Lawyers and Judicial Law Clerks","134710"},
            {"Podiatrists","136180"},
            {"Lawyers","136260"},
            {"Airline Pilot","136400"},
            {"Natural Sciences Managers","136570"},
            {"Marketing Managers","140660"},
            {"Computer and Information Systems Managers","141000"},
            {"Architectural and Engineering Manager","141650"},
            {"Petroleum Engineers","149590"},
            {"Nurse Anesthetists","160250"},
            {"Prosthodontists","161020"},
            {"Dentists, All Other Specialists","171040"},
            {"Dentists, General","172350"},
            {"Dentists","177130"},
            {"Pediatricians, General","183180"},
            {"Chief Executives","185850"},
            {"Family and General Practitioners","192120"},
            {"Psychiatrists","193680"},
            {"Internists, General","196520"},
            {"Physicians and Surgeons, All Other","197700"},
            {"Physicians and Surgeons","202450"},
            {"Orthodontists","221390"},
            {"Obstetricians and Gynecologists","222400"},
            {"Oral and Maxillofacial Surgeons","233900"},
            {"Surgeons","247520"},
            {"Anesthesiologist","258100"}
    };

    public static String[] generateProfession(Person person) {
        if(person != null && person.mEducationLevel != null && person.mSocialClass != null) {
            //HS: 33,176, 9.4% unemployed -- 21
            //SC: 39,936, 6.8% unemployed -- 36
            //CG: 54,756, 4.9% unemployed -- 63
            //PG: 80,652, 2.5% unemployed -- 86

            int index;
            float unemployedChance;

            if(person.mEducationLevel == EducationLevel.HIGH_SCHOOL) {
                index = Util.generateRandomIntInRange(0, 210);
                unemployedChance = 0.094f;
            } else if(person.mEducationLevel == EducationLevel.SOME_COLLEGE) {
                index = Util.generateRandomIntInRange(211, 360);
                unemployedChance = 0.068f;
            } else if(person.mEducationLevel == EducationLevel.COLLEGE_GRADUATE) {
                index = Util.generateRandomIntInRange(361, 630);
                unemployedChance = 0.049f;
            } else {
                index = Util.generateRandomIntInRange(631, professions.length - 1);
                unemployedChance = 0.025f;
            }

            double random = Math.random();

            if((person.mAge >= 62 && random <= .5f) || person.mAge > 75) {
                float baseRetirementSalary;

                if (person.mSocialClass == SocialClass.LOWER) {
                    baseRetirementSalary = 35000;
                } else if (person.mSocialClass == SocialClass.WORKING) {
                    baseRetirementSalary = 45000;
                } else if (person.mSocialClass == SocialClass.MIDDLE) {
                    baseRetirementSalary = 60000;
                } else if (person.mSocialClass == SocialClass.UPPER) {
                    baseRetirementSalary = 150000;
                } else if (person.mSocialClass == SocialClass.ELITE) {
                    baseRetirementSalary = 1000000;
                } else {
                    baseRetirementSalary = 100000000;
                }

                return new String[] { "Retired", String.valueOf((int)(baseRetirementSalary * Util.generateRandomFloatInRange(.8f, 1.2f)))};
            }

            if(random <= unemployedChance) {
                return new String[] { "Unemployed", "0" };
            }

            return professions[index];
        } else {
            throw new IllegalStateException("Education Level, and Social Class must be set before calling this.");
        }

    }
}